---
title: 'Chain parameters'
description: Information about important system parameters for public Arbitrum chains
user_story: As a developer, I want to understand the system parameters for the public Arbitrum chains.
content_type: overview
---

| Param                | Description                                                                                               | Arbitrum One                                                                    | Arbitrum Nova                                                               | Arb Sepolia                                                                       |
| -------------------- | --------------------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------- | --------------------------------------------------------------------------- | --------------------------------------------------------------------------------- |
| Dispute window       | Time for assertions to get confirmed during which validators can issue a challenge                        | @arbOneDisputeWindowBlocks@ blocks (~ @arbOneDisputeWindowDays@ days )          | @novaDisputeWindowBlocks@ blocks (~ @novaDisputeWindowDays@ days)           | @sepoliaDisputeWindowBlocks@ blocks (~ @sepoliaDisputeWindowMinutes@ minutes)     |
| Base stake           | Amount of stake required for a validator to make an assertion                                             | @arbOneBaesStakeEth@ ETH                                                        | @novaBaesStakeEth@ ETH                                                      | @sepoliaBaesStakeEth@ Sepolia ETH                                                 |
| Force-include period | Period after which a delayed message can be included into the inbox without any action from the Sequencer | @arbOneForceIncludePeriodBlocks@ blocks / @arbOneForceIncludePeriodHours@ hours | @novaForceIncludePeriodBlocks@ blocks / @novaForceIncludePeriodHours@ hours | @sepoliaForceIncludePeriodBlocks@ blocks / @sepoliaForceIncludePeriodHours@ hours |
| Gas speed limit      | Target gas/sec, over which the congestion mechanism activates                                             | @arbOneGasSpeedLimitGasPerSec@ gas/sec                                          | @novaGasSpeedLimitGasPerSec@ gas/sec                                        | @sepoliaGasSpeedLimitGasPerSec@ gas/sec                                           |
| Gas price floor      | Minimum gas price                                                                                         | @arbOneGasFloorGwei@ gwei                                                       | @novaGasFloorGwei@ gwei                                                     | @sepoliaGasFloorGwei@ gwei                                                        |
| Block gas limit      | Maximum amount of gas that all the transactions inside a block are allowed to consume                     | @arbOneBlockGasLimit@                                                           | @novaBlockGasLimit@                                                         | @sepoliaBlockGasLimit@                                                            |
