// Single source of truth for internal doc redirects. Consumed by next.config.mjs.
// Entries between the AUTO-GENERATED markers are maintained by `pnpm move-doc`.
import { legacyRedirects } from './redirects.legacy.mjs';

/** @type {{ source: string, destination: string, permanent: boolean }[]} */
export const redirects = [
  // AUTO-GENERATED REDIRECTS START
  {
    source: '/docs/launch-arbitrum-chain/run-a-node/run-batch-poster',
    destination: '/docs/run-a-node/run-batch-poster',
    permanent: true,
  },
  {
    source: '/docs/launch-arbitrum-chain/run-a-node/run-split-validator-node',
    destination: '/docs/run-a-node/run-split-validator-node',
    permanent: true,
  },
  {
    source: '/docs/launch-arbitrum-chain/run-a-node/high-availability-sequencer-docs',
    destination: '/docs/run-a-node/high-availability-sequencer-docs',
    permanent: true,
  },
  {
    source: '/docs/launch-arbitrum-chain/run-a-node',
    destination: '/docs/run-a-node',
    permanent: true,
  },
  // AUTO-GENERATED REDIRECTS END

  // Legacy docs.arbitrum.io URLs (root-level, pre-migration). Generated by
  // `pnpm redirects:legacy`; unportable entries are in redirects.legacy.todo.json.
  // Listed last so a hand-written or move-doc entry above always wins.
  ...legacyRedirects,
];
