// GENERATED by scripts/generate-current-redirects.mjs — do not edit by hand.
// Regenerate with `pnpm redirects:current`.
//
// Every URL docs.arbitrum.io serves today (Docusaurus, root-level) -> this site's /docs paths.
// Distinct from redirects.legacy.mjs, which ports upstream's own pre-restructure redirect map.
// Unresolvable pages are listed in redirects.current.todo.json.
//
// permanent: true (308) throughout. Moving the whole corpus under /docs is a permanent site
// restructure, and 308 is what passes the old URLs' search ranking to the new ones — the point
// of the exercise. The legacy generator copies upstream's per-entry flag instead because it is
// porting someone else's decisions; here there is no upstream flag to copy.
/** @type {{ source: string, destination: string, permanent: boolean }[]} */
export const currentRedirects = [
  {
    source: '/arbitrum-bridge/bridge-transaction-traceability',
    destination: '/docs/arbitrum-bridge/bridge-transaction-traceability',
    permanent: true,
  },
  {
    source: '/arbitrum-bridge/embedded-bridge-widget',
    destination: '/docs/arbitrum-bridge/embedded-bridge-widget',
    permanent: true,
  },
  {
    source: '/arbitrum-bridge/quickstart',
    destination: '/docs/arbitrum-bridge/quickstart',
    permanent: true,
  },
  {
    source: '/arbitrum-bridge/troubleshooting',
    destination: '/docs/arbitrum-bridge/troubleshooting',
    permanent: true,
  },
  {
    source: '/arbitrum-bridge/usdc-arbitrum-one',
    destination: '/docs/arbitrum-bridge/usdc-arbitrum-one',
    permanent: true,
  },
  {
    source: '/arbitrum-bridge/withdrawal-monitoring',
    destination: '/docs/arbitrum-bridge/withdrawal-monitoring',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials',
    destination: '/docs/arbitrum-essentials',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/arbitrum-vs-ethereum/block-numbers-and-time',
    destination: '/docs/arbitrum-essentials/arbitrum-vs-ethereum/block-numbers-and-time',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/arbitrum-vs-ethereum/comparison-overview',
    destination: '/docs/arbitrum-essentials/arbitrum-vs-ethereum/comparison-overview',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/arbitrum-vs-ethereum/nonce-management',
    destination: '/docs/arbitrum-essentials/arbitrum-vs-ethereum/nonce-management',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/arbitrum-vs-ethereum/rpc-methods',
    destination: '/docs/arbitrum-essentials/arbitrum-vs-ethereum/rpc-methods',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/arbitrum-vs-ethereum/solidity-support',
    destination: '/docs/arbitrum-essentials/arbitrum-vs-ethereum/solidity-support',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/bridging/configure-token-gateway/custom',
    destination: '/docs/arbitrum-essentials/bridging/configure-token-gateway/custom',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/bridging/configure-token-gateway/generic-custom',
    destination: '/docs/arbitrum-essentials/bridging/configure-token-gateway/generic-custom',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/bridging/configure-token-gateway/standard',
    destination: '/docs/arbitrum-essentials/bridging/configure-token-gateway/standard',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/bridging/cross-chain-messaging',
    destination: '/docs/arbitrum-essentials/bridging/cross-chain-messaging',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/bridging/custom-gas-token-chains',
    destination: '/docs/arbitrum-essentials/bridging/custom-gas-token-chains',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/bridging/deposit/eth-and-messages',
    destination: '/docs/arbitrum-essentials/bridging/deposit/eth-and-messages',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/bridging/deposit/tokens',
    destination: '/docs/arbitrum-essentials/bridging/deposit/tokens',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/bridging/l1-l3-teleportation',
    destination: '/docs/arbitrum-essentials/bridging/l1-l3-teleportation',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/bridging/overview',
    destination: '/docs/arbitrum-essentials/bridging/overview',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/bridging/withdraw/eth-and-messages',
    destination: '/docs/arbitrum-essentials/bridging/withdraw/eth-and-messages',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/bridging/withdraw/tokens',
    destination: '/docs/arbitrum-essentials/bridging/withdraw/tokens',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/how-to-estimate-gas',
    destination: '/docs/arbitrum-essentials/how-to-estimate-gas',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/how-to-get-l2block-on-l1',
    destination: '/docs/arbitrum-essentials/how-to-get-l2block-on-l1',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/nodeinterface/overview',
    destination: '/docs/arbitrum-essentials/nodeinterface/overview',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/nodeinterface/reference',
    destination: '/docs/arbitrum-essentials/nodeinterface/reference',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/oracles/overview-oracles',
    destination: '/docs/oracles/overview-oracles',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/precompiles/overview',
    destination: '/docs/arbitrum-essentials/precompiles/overview',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/precompiles/reference',
    destination: '/docs/arbitrum-essentials/precompiles/reference',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/public-chains',
    destination: '/docs/arbitrum-essentials/public-chains',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/reference/chain-params',
    destination: '/docs/arbitrum-essentials/reference/chain-params',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/reference/contract-addresses',
    destination: '/docs/arbitrum-essentials/reference/contract-addresses',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/reference/debugging-tools',
    destination: '/docs/arbitrum-essentials/reference/debugging-tools',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/reference/development-frameworks',
    destination: '/docs/arbitrum-essentials/reference/development-frameworks',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/reference/mainnet-risks',
    destination: '/docs/arbitrum-essentials/reference/mainnet-risks',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/reference/monitoring-tools-block-explorers',
    destination: '/docs/arbitrum-essentials/reference/monitoring-tools-block-explorers',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/reference/node-providers',
    destination: '/docs/arbitrum-essentials/reference/node-providers',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/reference/solidity-references',
    destination: '/docs/arbitrum-essentials/reference/solidity-references',
    permanent: true,
  },
  {
    source: '/arbitrum-essentials/reference/web3-libraries-tools',
    destination: '/docs/arbitrum-essentials/reference/web3-libraries-tools',
    permanent: true,
  },
  {
    source: '/audit-reports',
    destination: '/docs/audit-reports',
    permanent: true,
  },
  {
    source: '/build-decentralized-apps/machine-payments-protocol',
    destination: '/docs/build-decentralized-apps/machine-payments-protocol',
    permanent: true,
  },
  {
    source: '/build-decentralized-apps/quickstart-create-a-token',
    destination: '/docs/build-decentralized-apps/quickstart-create-a-token',
    permanent: true,
  },
  {
    source: '/build-decentralized-apps/quickstart-solidity-remix',
    destination: '/docs/build-decentralized-apps/quickstart-solidity-remix',
    permanent: true,
  },
  {
    source: '/for-devs/contribute',
    destination: '/docs/contribute',
    permanent: true,
  },
  {
    source: '/for-devs/dev-tools-and-resources/chain-info',
    destination: '/docs/chain-info',
    permanent: true,
  },
  {
    source: '/for-devs/oracles/api3',
    destination: '/docs/oracles/api3/api3',
    permanent: true,
  },
  {
    source: '/for-devs/oracles/chainlink',
    destination: '/docs/oracles/chainlink/chainlink',
    permanent: true,
  },
  {
    source: '/for-devs/oracles/chronicle',
    destination: '/docs/oracles/chronicle/chronicle',
    permanent: true,
  },
  {
    source: '/for-devs/oracles/DIA',
    destination: '/docs/oracles/DIA/dia',
    permanent: true,
  },
  {
    source: '/for-devs/oracles/ora',
    destination: '/docs/oracles/ora/ora',
    permanent: true,
  },
  {
    source: '/for-devs/oracles/oracles-content-map',
    destination: '/docs/oracles',
    permanent: true,
  },
  {
    source: '/for-devs/oracles/supra/supras-price-feed',
    destination: '/docs/oracles/supra/use-supras-price-feed-oracle',
    permanent: true,
  },
  {
    source: '/for-devs/oracles/supra/supras-vrf',
    destination: '/docs/oracles/supra/use-supras-vrf',
    permanent: true,
  },
  {
    source: '/for-devs/oracles/trellor',
    destination: '/docs/oracles/trellor/trellor',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/Circle/usdc-paymaster-quickstart',
    destination: '/docs/third-party-docs/Circle/usdc-paymaster-quickstart',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/Circle/usdc-quickstart-guide',
    destination: '/docs/third-party-docs/Circle/usdc-quickstart-guide',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/Codex',
    destination: '/docs/third-party-docs/Codex/codex',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/contribute',
    destination: '/docs/third-party-docs/contribute',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/Covalent',
    destination: '/docs/third-party-docs/Covalent/covalent',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/Crossmint',
    destination: '/docs/third-party-docs/Crossmint/crossmint',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/Envio',
    destination: '/docs/third-party-docs/Envio/envio',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/Flair',
    destination: '/docs/third-party-docs/Flair/flair',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/Gelato/gelato-vrf',
    destination: '/docs/third-party-docs/Gelato/gelato-vrf',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/LayerZero',
    destination: '/docs/third-party-docs/LayerZero/layerzero',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/MetaMask',
    destination: '/docs/third-party-docs/MetaMask/metamask',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/Moralis',
    destination: '/docs/third-party-docs/Moralis/moralis',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/OKX',
    destination: '/docs/third-party-docs/OKX/okx',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/Openfort',
    destination: '/docs/third-party-docs/Openfort/openfort',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/Particle',
    destination: '/docs/third-party-docs/Particle/particle',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/QuickNode/backfill-templates',
    destination: '/docs/third-party-docs/QuickNode/backfill-templates',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/Reactive',
    destination: '/docs/third-party-docs/Reactive/reactive',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/Reown',
    destination: '/docs/third-party-docs/Reown/reown',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/TheGraph',
    destination: '/docs/third-party-docs/TheGraph/thegraph',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/Venly',
    destination: '/docs/third-party-docs/Venly/venly',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/Webacy',
    destination: '/docs/third-party-docs/Webacy/webacy',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/Zerion',
    destination: '/docs/third-party-docs/Zerion/zerion',
    permanent: true,
  },
  {
    source: '/for-devs/third-party-docs/ZeroDev/zero-dev',
    destination: '/docs/third-party-docs/ZeroDev/zero-dev',
    permanent: true,
  },
  {
    source: '/for-devs/troubleshooting-building',
    destination: '/docs/build-decentralized-apps/troubleshooting-building',
    permanent: true,
  },
  {
    source: '/get-started/arbitrum-introduction',
    destination: '/docs/get-started/arbitrum-introduction',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/bold/bold-economics-of-disputes',
    destination: '/docs/how-arbitrum-works/bold/bold-economics-of-disputes',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/bold/bold-faq',
    destination: '/docs/how-arbitrum-works/bold/bold-faq',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/bold/bold-technical-deep-dive',
    destination: '/docs/how-arbitrum-works/bold/bold-technical-deep-dive',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/bold/gentle-introduction',
    destination: '/docs/how-arbitrum-works/bold/gentle-introduction',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/bold/how-bold-bisection-works',
    destination: '/docs/how-arbitrum-works/bold/how-bold-bisection-works',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/deep-dives/anytrust-protocol',
    destination: '/docs/how-arbitrum-works/deep-dives/anytrust-protocol',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/deep-dives/arbos',
    destination: '/docs/how-arbitrum-works/deep-dives/arbos',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/deep-dives/assertions',
    destination: '/docs/how-arbitrum-works/deep-dives/assertions',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/deep-dives/batchposter',
    destination: '/docs/how-arbitrum-works/deep-dives/batchposter',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/deep-dives/finality',
    destination: '/docs/how-arbitrum-works/deep-dives/finality',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/deep-dives/gas-and-fees',
    destination: '/docs/how-arbitrum-works/deep-dives/gas-and-fees',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/deep-dives/l1-to-l2-messaging',
    destination: '/docs/how-arbitrum-works/deep-dives/l1-to-l2-messaging',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/deep-dives/l2-to-l1-messaging',
    destination: '/docs/how-arbitrum-works/deep-dives/l2-to-l1-messaging',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/deep-dives/sequencer',
    destination: '/docs/how-arbitrum-works/deep-dives/sequencer',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/deep-dives/sequencer-transaction-flow',
    destination: '/docs/how-arbitrum-works/deep-dives/sequencer-transaction-flow',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/deep-dives/stf',
    destination: '/docs/how-arbitrum-works/deep-dives/stf',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/deep-dives/token-bridging',
    destination: '/docs/how-arbitrum-works/deep-dives/token-bridging',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/deep-dives/transaction-lifecycle',
    destination: '/docs/how-arbitrum-works/deep-dives/transaction-lifecycle',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/inside-arbitrum-nitro',
    destination: '/docs/how-arbitrum-works/inside-arbitrum-nitro',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/priority-gas-auction/fast-feed',
    destination: '/docs/how-arbitrum-works/priority-gas-auction/fast-feed',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/priority-gas-auction/pga',
    destination: '/docs/how-arbitrum-works/priority-gas-auction/pga',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/reference/arbos-reference',
    destination: '/docs/how-arbitrum-works/reference/arbos-reference',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/reference/finality-and-reorgs',
    destination: '/docs/how-arbitrum-works/reference/finality-and-reorgs',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/reference/geth',
    destination: '/docs/how-arbitrum-works/reference/geth',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/reference/stf-inputs',
    destination: '/docs/how-arbitrum-works/reference/stf-inputs',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/timeboost/gentle-introduction',
    destination: '/docs/how-arbitrum-works/timeboost/gentle-introduction',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/timeboost/how-to-use-timeboost',
    destination: '/docs/how-arbitrum-works/timeboost/how-to-use-timeboost',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/timeboost/timeboost-faq',
    destination: '/docs/how-arbitrum-works/timeboost/timeboost-faq',
    permanent: true,
  },
  {
    source: '/how-arbitrum-works/timeboost/troubleshoot-timeboost',
    destination: '/docs/how-arbitrum-works/timeboost/troubleshoot-timeboost',
    permanent: true,
  },
  {
    source: '/intro/glossary',
    destination: '/docs/glossary',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/additional-configuration-parameters',
    destination:
      '/docs/launch-arbitrum-chain/configuration/core/additional-configuration-parameters',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/batch-poster/config-batch-poster',
    destination:
      '/docs/launch-arbitrum-chain/configuration/sequencer/batch-posting-assertion-control',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/batch-poster/enable-4844-blobs',
    destination:
      '/docs/launch-arbitrum-chain/configuration/data-availability/enable-post-4844-blobs',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/batch-poster/fee-tuning',
    destination: '/docs/launch-arbitrum-chain/configuration/sequencer/batch-poster-fee-tuning',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/chainConfig-reference',
    destination: '/docs/launch-arbitrum-chain/configuration/chain-config-reference',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/costs/aep-overview',
    destination: '/docs/launch-arbitrum-chain/configuration/costs/aep-fee-router-introduction',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/costs/aep-router-contracts',
    destination: '/docs/launch-arbitrum-chain/configuration/costs/set-up-aep-fee-router',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/costs/configure-native-mint-burn',
    destination:
      '/docs/launch-arbitrum-chain/configuration/costs/configure-native-mint-burn-gas-token',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/costs/custom-gas-token-anytrust',
    destination: '/docs/launch-arbitrum-chain/configuration/costs/use-a-custom-gas-token-anytrust',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/costs/custom-gas-token-rollup',
    destination: '/docs/launch-arbitrum-chain/configuration/costs/use-a-custom-gas-token-rollup',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/costs/dynamic-pricing',
    destination:
      '/docs/launch-arbitrum-chain/configuration/costs/dynamic-pricing-for-arbitrum-chains',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/costs/fee-management',
    destination: '/docs/launch-arbitrum-chain/configuration/costs/fee-management',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/costs/gas-optimization',
    destination: '/docs/launch-arbitrum-chain/configuration/costs/gas-optimization-tools',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/costs/gas-target',
    destination: '/docs/launch-arbitrum-chain/operate/gas-target',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/costs/parent-chain-data-fee-pricing',
    destination: '/docs/launch-arbitrum-chain/configuration/costs/parent-chain-data-fee-pricing',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/costs/priority-fees',
    destination: '/docs/launch-arbitrum-chain/configuration/costs/priority-fees',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/costs/reporting-on-fees',
    destination: '/docs/launch-arbitrum-chain/configuration/costs/reporting-on-fees',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/costs/revenue-routing',
    destination: '/docs/launch-arbitrum-chain/configuration/costs/revenue-routing',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/data-availability/config-data-availability',
    destination:
      '/docs/launch-arbitrum-chain/configuration/data-availability/config-data-availability',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/data-availability/configure-dac',
    destination:
      '/docs/launch-arbitrum-chain/configuration/data-availability/data-availability-committees/configure-dac',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/data-availability/dac-configuration-defaults',
    destination:
      '/docs/launch-arbitrum-chain/configuration/data-availability/data-availability-committees/dac-configuration-defaults',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/data-availability/dac-das-operations',
    destination:
      '/docs/launch-arbitrum-chain/configuration/data-availability/data-availability-committees/dac-das-operations',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/data-availability/dac-get-started',
    destination:
      '/docs/launch-arbitrum-chain/configuration/data-availability/data-availability-committees/get-started',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/data-availability/das-docker-deployment',
    destination:
      '/docs/launch-arbitrum-chain/configuration/data-availability/das-docker-deployment',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/data-availability/das-rpc-method-reference',
    destination:
      '/docs/launch-arbitrum-chain/configuration/data-availability/data-availability-committees/das-rpc-method-reference',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/data-availability/deploy-das',
    destination:
      '/docs/launch-arbitrum-chain/configuration/data-availability/data-availability-committees/deploy-das',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/data-availability/deploy-mirror-das',
    destination:
      '/docs/launch-arbitrum-chain/configuration/data-availability/data-availability-committees/deploy-mirror-das',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/execution/smart-contract-size-limit',
    destination: '/docs/launch-arbitrum-chain/configuration/core/config-smart-contract-size-limit',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/sequencer/chain-finality',
    destination: '/docs/launch-arbitrum-chain/configuration/validation/arbitrum-chain-finality',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/sequencer/compliance-filtering',
    destination: '/docs/launch-arbitrum-chain/configuration/sequencer/compliance-filtering',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/sequencer/pga',
    destination: '/docs/launch-arbitrum-chain/configuration/sequencer/pga',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/sequencer/sequencer-config-reference',
    destination: '/docs/launch-arbitrum-chain/configuration/sequencer/sequencer-config-reference',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/sequencer/sequencer-timing-adjustments',
    destination:
      '/docs/launch-arbitrum-chain/configuration/sequencer/config-sequencer-timing-adjustments',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/sequencer/timeboost',
    destination:
      '/docs/launch-arbitrum-chain/configuration/sequencer/timeboost-for-arbitrum-chains',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/validation/assertion-control',
    destination:
      '/docs/launch-arbitrum-chain/configuration/sequencer/batch-posting-assertion-control',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/validation/bold',
    destination:
      '/docs/launch-arbitrum-chain/configuration/sequencer/bold-adoption-for-arbitrum-chains',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/validation/bond-and-validator',
    destination:
      '/docs/launch-arbitrum-chain/configuration/validation/stake-and-validator-configurations',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/validation/challenge-period',
    destination:
      '/docs/launch-arbitrum-chain/configuration/validation/customizable-challenge-period',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/validation/fast-withdrawals',
    destination: '/docs/launch-arbitrum-chain/configuration/validation/fast-withdrawals',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/chain-config/validation/test-chain-configuration',
    destination: '/docs/launch-arbitrum-chain/configuration/validation/test-chain-configuration',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/deploy/canonical-factory-contracts',
    destination: '/docs/launch-arbitrum-chain/deploy/canonical-factory-contracts',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/deploy/configure-node',
    destination: '/docs/launch-arbitrum-chain/arbitrum-chain-sdk-preparing-node-config',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/deploy/custom-genesis-state',
    destination: '/docs/launch-arbitrum-chain/deploy/custom-genesis-state',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/deploy/deploy-chain',
    destination: '/docs/launch-arbitrum-chain/deploy/deploying-an-arbitrum-chain',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/deploy/token-bridge',
    destination: '/docs/launch-arbitrum-chain/deploy/deploying-token-bridge',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/deploy/token-bridge-troubleshooting',
    destination: '/docs/launch-arbitrum-chain/deploy/token-bridge-troubleshooting',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/extend-the-protocol/arbos',
    destination: '/docs/launch-arbitrum-chain/configuration/core/customize-arbos',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/extend-the-protocol/da-api-guide',
    destination: '/docs/launch-arbitrum-chain/integrations/da-api-integration-guide',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/extend-the-protocol/precompiles',
    destination: '/docs/launch-arbitrum-chain/configuration/core/customize-precompile',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/extend-the-protocol/stf',
    destination: '/docs/launch-arbitrum-chain/configuration/core/customize-stf',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/integrations/bp-kms-signing-services',
    destination: '/docs/launch-arbitrum-chain/integrations/bp-kms-signing-services',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/integrations/bridge-ui',
    destination: '/docs/launch-arbitrum-chain/integrations/bridge-ui',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/integrations/bridged-usdc',
    destination: '/docs/launch-arbitrum-chain/integrations/bridged-usdc-standard',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/integrations/exchange-integration-checklist',
    destination: '/docs/launch-arbitrum-chain/integrations/exchange-integration-checklist',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/integrations/infrastructure-providers',
    destination: '/docs/launch-arbitrum-chain/third-party-integrations/third-party-providers',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/migrate/between-raases',
    destination: '/docs/launch-arbitrum-chain/migrate/migrate-between-raases',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/migrate/from-another-stack',
    destination: '/docs/launch-arbitrum-chain/migrate/migrate-from-another-stack',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/operate/arbos-upgrade',
    destination: '/docs/launch-arbitrum-chain/operate/arbos-upgrade',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/operate/batch-poster-troubleshooting',
    destination: '/docs/launch-arbitrum-chain/configuration/sequencer/batch-poster-troubleshooting',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/operate/bold-upgrade-playbook',
    destination: '/docs/launch-arbitrum-chain/operate/bold-upgrade-playbook',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/operate/bp-recovery',
    destination: '/docs/launch-arbitrum-chain/operate/bp-recovery',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/operate/error-index',
    destination: '/docs/launch-arbitrum-chain/operate/error-index',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/operate/key-rotation',
    destination: '/docs/launch-arbitrum-chain/operate/key-rotation',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/operate/monitoring',
    destination: '/docs/launch-arbitrum-chain/operate/monitoring-tools-and-considerations',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/operate/ownership-and-access',
    destination: '/docs/launch-arbitrum-chain/operate/ownership-access-control',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/operate/post-launch-deployments',
    destination: '/docs/launch-arbitrum-chain/operate/post-launch-contract-deployments',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/operate/sequencer-troubleshooting',
    destination: '/docs/launch-arbitrum-chain/operate/sequencer-troubleshooting',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/operate/state-growth',
    destination: '/docs/launch-arbitrum-chain/operate/state-growth',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/operate/upgrade-runbook',
    destination: '/docs/launch-arbitrum-chain/operate/upgrade-runbook',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/operate/validator-troubleshooting',
    destination: '/docs/launch-arbitrum-chain/operate/validator-troubleshooting',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/overview/faq',
    destination: '/docs/launch-arbitrum-chain/troubleshooting-building-arbitrum-chain',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/overview/introduction',
    destination: '/docs/launch-arbitrum-chain/overview/a-gentle-introduction',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/overview/license',
    destination: '/docs/launch-arbitrum-chain/overview/aep-license',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/overview/public-preview',
    destination: '/docs/launch-arbitrum-chain/overview/public-preview-expectations',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/quickstart/l3-rollup-from-scratch',
    destination: '/docs/launch-arbitrum-chain/quickstart/deploy-your-first-rollup',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/quickstart/l3-rollup-testnet',
    destination: '/docs/launch-arbitrum-chain/quickstart/run-testnet-infrastructure-first-rollup',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/quickstart/sdk-introduction',
    destination: '/docs/launch-arbitrum-chain/overview/arbitrum-chain-sdk-introduction',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/run-a-node/batch-poster',
    destination: '/docs/run-a-node/run-batch-poster',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/run-a-node/high-availability-sequencer',
    destination: '/docs/run-a-node/high-availability-sequencer-docs',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/run-a-node/run-full-node-with-helm',
    destination: '/docs/launch-arbitrum-chain/run-a-node/run-full-node-with-helm',
    permanent: true,
  },
  {
    source: '/launch-arbitrum-chain/run-a-node/split-validator-node',
    destination: '/docs/run-a-node/run-split-validator-node',
    permanent: true,
  },
  {
    source: '/learn-more/faq',
    destination: '/docs/get-started/faq',
    permanent: true,
  },
  {
    source: '/node-running/faq',
    destination: '/docs/run-a-node/faq',
    permanent: true,
  },
  {
    source: '/notices/arbos51-upgrade-notice',
    destination: '/docs/notices/arbos51-upgrade-notice',
    permanent: true,
  },
  {
    source: '/notices/arbos61-upgrade-notice',
    destination: '/docs/notices/arbos61-upgrade-notice',
    permanent: true,
  },
  {
    source: '/notices/fusaka-upgrade-notice',
    destination: '/docs/notices/fusaka-upgrade-notice',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/arbos-releases/arbos11',
    destination: '/docs/run-a-node/arbos-releases/arbos11',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/arbos-releases/arbos20',
    destination: '/docs/run-a-node/arbos-releases/arbos20',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/arbos-releases/arbos32',
    destination: '/docs/run-a-node/arbos-releases/arbos32',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/arbos-releases/arbos40',
    destination: '/docs/run-a-node/arbos-releases/arbos40',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/arbos-releases/arbos51',
    destination: '/docs/run-a-node/arbos-releases/arbos51',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/arbos-releases/arbos61',
    destination: '/docs/run-a-node/arbos-releases/arbos61',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/arbos-releases/overview',
    destination: '/docs/run-a-node/arbos-releases/overview',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/assign-node-roles',
    destination: '/docs/run-a-node/assign-node-roles',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/beacon-nodes-historical-blobs',
    destination: '/docs/run-a-node/beacon-nodes-historical-blobs',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/data-availability',
    destination: '/docs/run-a-node/data-availability',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/l1-ethereum-beacon-chain-rpc-providers',
    destination: '/docs/run-a-node/l1-ethereum-beacon-chain-rpc-providers',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/more-types/run-archive-node',
    destination: '/docs/run-a-node/more-types/run-archive-node',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/more-types/run-classic-node',
    destination: '/docs/run-a-node/more-types/run-classic-node',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/more-types/run-validator-node',
    destination: '/docs/run-a-node/more-types/run-validator-node',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/nitro-support-policy',
    destination: '/docs/run-a-node/nitro-support-policy',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/nitro/build-nitro-locally',
    destination: '/docs/run-a-node/nitro/build-nitro-locally',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/nitro/cli-flags-reference',
    destination: '/docs/run-a-node/nitro/cli-flags-reference',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/nitro/configuration-system',
    destination: '/docs/run-a-node/nitro/configuration-system',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/nitro/da-tools-reference',
    destination: '/docs/run-a-node/nitro/da-tools-reference',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/nitro/docker-and-cli-binaries',
    destination: '/docs/run-a-node/nitro/docker-and-cli-binaries',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/nitro/how-to-convert-databases-from-leveldb-to-pebble',
    destination: '/docs/run-a-node/nitro/how-to-convert-databases-from-leveldb-to-pebble',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/nitro/migrate-state-and-history-from-classic',
    destination: '/docs/run-a-node/nitro/migrate-state-and-history-from-classic',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/nitro/nitro-database-snapshots',
    destination: '/docs/run-a-node/nitro/nitro-database-snapshots',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/nitro/node-tuning-and-monitoring',
    destination: '/docs/run-a-node/nitro/node-tuning-and-monitoring',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/overview',
    destination: '/docs/run-a-node/overview',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/run-feed-relay',
    destination: '/docs/run-a-node/run-feed-relay',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/run-full-node',
    destination: '/docs/run-a-node/run-full-node',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/run-local-full-chain-simulation',
    destination: '/docs/run-a-node/run-local-full-chain-simulation',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/run-nitro-dev-node',
    destination: '/docs/run-a-node/run-nitro-dev-node',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/sequencer/read-sequencer-feed',
    destination: '/docs/run-a-node/sequencer/read-sequencer-feed',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/sequencer/run-sequencer-coordination-manager',
    destination: '/docs/run-a-node/sequencer/run-sequencer-coordination-manager',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/sequencer/run-sequencer-node',
    destination: '/docs/run-a-node/sequencer/run-sequencer-node',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/start-here',
    destination: '/docs/run-a-node/start-here',
    permanent: true,
  },
  {
    source: '/run-arbitrum-node/troubleshooting',
    destination: '/docs/run-a-node/troubleshooting',
    permanent: true,
  },
  {
    source: '/stylus-by-example/applications/erc20',
    destination: '/docs/stylus/stylus-by-example/applications/erc20',
    permanent: true,
  },
  {
    source: '/stylus-by-example/applications/erc721',
    destination: '/docs/stylus/stylus-by-example/applications/erc721',
    permanent: true,
  },
  {
    source: '/stylus-by-example/applications/multi_call',
    destination: '/docs/stylus/stylus-by-example/applications/multi_call',
    permanent: true,
  },
  {
    source: '/stylus-by-example/applications/vending_machine',
    destination: '/docs/stylus/stylus-by-example/applications/vending_machine',
    permanent: true,
  },
  {
    source: '/stylus-by-example/basic_examples/abi_decode',
    destination: '/docs/stylus/stylus-by-example/basic_examples/abi_decode',
    permanent: true,
  },
  {
    source: '/stylus-by-example/basic_examples/abi_encode',
    destination: '/docs/stylus/stylus-by-example/basic_examples/abi_encode',
    permanent: true,
  },
  {
    source: '/stylus-by-example/basic_examples/bytes_in_bytes_out',
    destination: '/docs/stylus/stylus-by-example/basic_examples/bytes_in_bytes_out',
    permanent: true,
  },
  {
    source: '/stylus-by-example/basic_examples/constants',
    destination: '/docs/stylus/stylus-by-example/basic_examples/constants',
    permanent: true,
  },
  {
    source: '/stylus-by-example/basic_examples/errors',
    destination: '/docs/stylus/stylus-by-example/basic_examples/errors',
    permanent: true,
  },
  {
    source: '/stylus-by-example/basic_examples/events',
    destination: '/docs/stylus/stylus-by-example/basic_examples/events',
    permanent: true,
  },
  {
    source: '/stylus-by-example/basic_examples/function',
    destination: '/docs/stylus/stylus-by-example/basic_examples/function',
    permanent: true,
  },
  {
    source: '/stylus-by-example/basic_examples/function_selector',
    destination: '/docs/stylus/stylus-by-example/basic_examples/function_selector',
    permanent: true,
  },
  {
    source: '/stylus-by-example/basic_examples/hashing',
    destination: '/docs/stylus/stylus-by-example/basic_examples/hashing',
    permanent: true,
  },
  {
    source: '/stylus-by-example/basic_examples/hello_world',
    destination: '/docs/stylus/stylus-by-example/basic_examples/hello_world',
    permanent: true,
  },
  {
    source: '/stylus-by-example/basic_examples/inheritance',
    destination: '/docs/stylus/stylus-by-example/basic_examples/inheritance',
    permanent: true,
  },
  {
    source: '/stylus-by-example/basic_examples/primitive_data_types',
    destination: '/docs/stylus/stylus-by-example/basic_examples/primitive_data_types',
    permanent: true,
  },
  {
    source: '/stylus-by-example/basic_examples/sending_ether',
    destination: '/docs/stylus/stylus-by-example/basic_examples/sending_ether',
    permanent: true,
  },
  {
    source: '/stylus-by-example/basic_examples/variables',
    destination: '/docs/stylus/stylus-by-example/basic_examples/variables',
    permanent: true,
  },
  {
    source: '/stylus-by-example/basic_examples/vm_affordances',
    destination: '/docs/stylus/stylus-by-example/basic_examples/vm_affordances',
    permanent: true,
  },
  {
    source: '/stylus/advanced/hostio-exports',
    destination: '/docs/stylus/advanced/hostio-exports',
    permanent: true,
  },
  {
    source: '/stylus/advanced/minimal-entrypoint-contracts',
    destination: '/docs/stylus/advanced/minimal-entrypoint-contracts',
    permanent: true,
  },
  {
    source: '/stylus/advanced/recommended-libraries',
    destination: '/docs/stylus/advanced/recommended-libraries',
    permanent: true,
  },
  {
    source: '/stylus/advanced/rust-to-solidity-differences',
    destination: '/docs/stylus/advanced/rust-to-solidity-differences',
    permanent: true,
  },
  {
    source: '/stylus/best-practices/gas-optimization',
    destination: '/docs/stylus/best-practices/gas-optimization',
    permanent: true,
  },
  {
    source: '/stylus/best-practices/security',
    destination: '/docs/stylus/best-practices/security',
    permanent: true,
  },
  {
    source: '/stylus/cli-tools/check-and-deploy',
    destination: '/docs/stylus/cli-tools/check-and-deploy',
    permanent: true,
  },
  {
    source: '/stylus/cli-tools/commands-reference',
    destination: '/docs/stylus/cli-tools/commands-reference',
    permanent: true,
  },
  {
    source: '/stylus/cli-tools/debugging-tx',
    destination: '/docs/stylus/cli-tools/debugging-tx',
    permanent: true,
  },
  {
    source: '/stylus/cli-tools/overview',
    destination: '/docs/stylus/cli-tools/overview',
    permanent: true,
  },
  {
    source: '/stylus/cli-tools/verify-contracts',
    destination: '/docs/stylus/cli-tools/verify-contracts',
    permanent: true,
  },
  {
    source: '/stylus/concepts/activation',
    destination: '/docs/stylus/concepts/activation',
    permanent: true,
  },
  {
    source: '/stylus/concepts/gas-metering',
    destination: '/docs/stylus/concepts/gas-metering',
    permanent: true,
  },
  {
    source: '/stylus/concepts/vm-differences',
    destination: '/docs/stylus/concepts/vm-differences',
    permanent: true,
  },
  {
    source: '/stylus/concepts/webassembly',
    destination: '/docs/stylus/concepts/webassembly',
    permanent: true,
  },
  {
    source: '/stylus/fundamentals/choose-your-path',
    destination: '/docs/stylus/fundamentals/choose-your-path',
    permanent: true,
  },
  {
    source: '/stylus/fundamentals/contracts',
    destination: '/docs/stylus/fundamentals/contracts',
    permanent: true,
  },
  {
    source: '/stylus/fundamentals/data-types/compound-types',
    destination: '/docs/stylus/fundamentals/data-types/compound-types',
    permanent: true,
  },
  {
    source: '/stylus/fundamentals/data-types/conversions-between-types',
    destination: '/docs/stylus/fundamentals/data-types/conversions-between-types',
    permanent: true,
  },
  {
    source: '/stylus/fundamentals/data-types/primitives',
    destination: '/docs/stylus/fundamentals/data-types/primitives',
    permanent: true,
  },
  {
    source: '/stylus/fundamentals/data-types/storage',
    destination: '/docs/stylus/fundamentals/data-types/storage',
    permanent: true,
  },
  {
    source: '/stylus/fundamentals/global-variables-and-functions',
    destination: '/docs/stylus/fundamentals/global-variables-and-functions',
    permanent: true,
  },
  {
    source: '/stylus/fundamentals/prerequisites',
    destination: '/docs/stylus/fundamentals/prerequisites',
    permanent: true,
  },
  {
    source: '/stylus/fundamentals/project-structure',
    destination: '/docs/stylus/fundamentals/project-structure',
    permanent: true,
  },
  {
    source: '/stylus/fundamentals/testing-contracts',
    destination: '/docs/stylus/fundamentals/testing-contracts',
    permanent: true,
  },
  {
    source: '/stylus/gentle-introduction',
    destination: '/docs/stylus/gentle-introduction',
    permanent: true,
  },
  {
    source: '/stylus/how-tos/caching-contracts',
    destination: '/docs/stylus/how-tos/caching-contracts',
    permanent: true,
  },
  {
    source: '/stylus/how-tos/deploying-non-rust-wasm-contracts',
    destination: '/docs/stylus/how-tos/deploying-non-rust-wasm-contracts',
    permanent: true,
  },
  {
    source: '/stylus/how-tos/exporting-abi',
    destination: '/docs/stylus/how-tos/exporting-abi',
    permanent: true,
  },
  {
    source: '/stylus/how-tos/importing-interfaces',
    destination: '/docs/stylus/how-tos/importing-interfaces',
    permanent: true,
  },
  {
    source: '/stylus/how-tos/optimizing-binaries',
    destination: '/docs/stylus/how-tos/optimizing-binaries',
    permanent: true,
  },
  {
    source: '/stylus/how-tos/trait-based-composition',
    destination: '/docs/stylus/how-tos/trait-based-composition',
    permanent: true,
  },
  {
    source: '/stylus/how-tos/using-constructors',
    destination: '/docs/stylus/how-tos/using-constructors',
    permanent: true,
  },
  {
    source: '/stylus/how-tos/verifying-contracts-arbiscan',
    destination: '/docs/stylus/how-tos/verifying-contracts-arbiscan',
    permanent: true,
  },
  {
    source: '/stylus/quickstart',
    destination: '/docs/stylus/quickstart',
    permanent: true,
  },
  {
    source: '/stylus/reference/opcode-hostio-pricing',
    destination: '/docs/stylus/reference/opcode-hostio-pricing',
    permanent: true,
  },
  {
    source: '/stylus/reference/overview',
    destination: '/docs/stylus/reference/overview',
    permanent: true,
  },
  {
    source: '/stylus/reference/rust-sdk-guide',
    destination: '/docs/stylus/reference/rust-sdk-guide',
    permanent: true,
  },
  {
    source: '/stylus/reference/stylus-toml-reference',
    destination: '/docs/stylus/reference/stylus-toml-reference',
    permanent: true,
  },
  {
    source: '/stylus/troubleshooting-building-stylus',
    destination: '/docs/stylus/troubleshooting-building-stylus',
    permanent: true,
  },
  {
    source: '/stylus/troubleshooting/common-issues',
    destination: '/docs/stylus/troubleshooting/common-issues',
    permanent: true,
  },
];
