// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Get started sidebar - shared entry point
  getStartedSidebar: [
    {
      type: 'doc',
      id: 'get-started/overview',
      label: 'Get started',
    },
    {
      type: 'doc',
      id: 'get-started/arbitrum-introduction',
      label: 'Arbitrum: introduction',
    },
    {
      type: 'category',
      label: 'Build apps',
      collapsed: true,
      items: [
        {
          type: 'doc',
          id: 'build-decentralized-apps/quickstart-solidity-remix',
          label: 'Build apps with Solidity',
        },
        {
          type: 'doc',
          id: 'stylus/quickstart',
          label: 'Build apps with Stylus',
        },
      ],
    },
    {
      type: 'link',
      label: 'Arbitrum essentials',
      href: '/arbitrum-essentials',
    },
    {
      type: 'link',
      label: 'Run an Arbitrum chain',
      href: '/launch-arbitrum-chain/overview/introduction',
    },
    {
      type: 'link',
      label: 'Run an Arbitrum node',
      href: '/run-arbitrum-node/overview',
    },
    {
      type: 'link',
      label: 'Arbitrum bridge',
      href: '/arbitrum-bridge/quickstart',
    },
    {
      type: 'link',
      label: 'How Arbitrum works',
      href: '/how-arbitrum-works/inside-arbitrum-nitro',
    },
    {
      type: 'doc',
      id: 'for-devs/dev-tools-and-resources/chain-info',
      label: 'Chain info',
    },
    {
      type: 'doc',
      id: 'intro/glossary',
      label: 'Glossary',
    },
    {
      type: 'doc',
      id: 'for-devs/contribute',
      label: 'Contribute',
    },
    {
      type: 'doc',
      id: 'learn-more/faq',
      label: 'FAQ',
    },
    {
      type: 'link',
      label: 'Notices',
      href: '/notices/arbos51-upgrade-notice',
    },
    {
      type: 'doc',
      label: 'Audit reports',
      id: 'audit-reports',
    },
    {
      type: 'category',
      label: 'Third-party docs',
      collapsed: true,
      items: [
        {
          type: 'category',
          label: 'Oracles',
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'for-devs/oracles/api3/api3',
            },
            {
              type: 'doc',
              id: 'for-devs/oracles/chainlink/chainlink',
            },
            {
              type: 'doc',
              id: 'for-devs/oracles/chronicle/chronicle',
            },
            {
              type: 'doc',
              id: 'for-devs/oracles/DIA/dia',
            },
            {
              type: 'doc',
              id: 'for-devs/oracles/ora/ora',
            },
            {
              type: 'doc',
              id: 'for-devs/oracles/supra/supras-price-feed',
            },
            {
              type: 'doc',
              id: 'for-devs/oracles/supra/supras-vrf',
            },
            {
              type: 'doc',
              id: 'for-devs/oracles/trellor/trellor',
            },
          ],
        },
        {
          type: 'autogenerated',
          dirName: 'for-devs/third-party-docs',
        },
      ],
    },
    {
      type: 'link',
      label: 'DAO docs',
      href: 'https://docs.arbitrum.foundation/gentle-intro-dao-governance',
    },
    {
      type: 'link',
      label: 'Prysm docs',
      href: 'https://www.offchainlabs.com/prysm/docs',
    },
  ],
  // Run Arbitrum Chain sidebar
  runArbitrumChainSidebar: [
    {
      type: 'category',
      label: 'Run an Arbitrum chain',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'launch-arbitrum-chain/overview/introduction',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'launch-arbitrum-chain/overview/license',
          label: 'Licensing',
        },
        {
          type: 'doc',
          id: 'launch-arbitrum-chain/overview/faq',
          label: 'FAQ',
        },
        {
          type: 'category',
          label: 'Quickstart',
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/quickstart/l3-rollup-from-scratch',
              label: `L3 rollup from scratch`,
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/quickstart/l3-rollup-testnet',
              label: 'L3 rollup infrastructure',
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/quickstart/sdk-introduction',
              label: 'Chain SDK overview',
            },
          ],
        },
        {
          type: 'category',
          label: 'Chain configuration',
          collapsed: true,
          items: [
            {
              type: 'category',
              label: 'Batch poster',
              collapsed: true,
              items: [
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/batch-poster/config-batch-poster',
                  label: `Batch poster`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/batch-poster/fee-tuning',
                  label: `Batch poster fee tuning`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/batch-poster/enable-4844-blobs',
                  label: `Enable EIP-4844 blobs`,
                },
              ],
            },
            {
              type: 'category',
              label: 'Costs',
              collapsed: true,
              items: [
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/costs/aep-overview',
                  label: `AEP overview`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/costs/aep-router-contracts',
                  label: `AEP router contracts`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/costs/calculate-aep-fees',
                  label: `AEP fee calculation`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/costs/reporting-on-fees',
                  label: `AEP reporting`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/costs/configure-native-mint-burn',
                  label: `Native mint and burn`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/costs/custom-gas-token-anytrust',
                  label: `Custom gas token (AnyTrust)`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/costs/custom-gas-token-rollup',
                  label: `Custom gas token (Rollup)`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/costs/dynamic-pricing',
                  label: `Dynamic pricing`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/costs/fee-management',
                  label: `Fee management`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/costs/gas-optimization',
                  label: `Gas optimization`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/costs/gas-target',
                  label: 'Gas target',
                },
              ],
            },
            {
              type: 'category',
              label: 'Data availability',
              collapsed: true,
              items: [
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/data-availability/config-data-availability',
                  label: `Data availability options`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/data-availability/dac-get-started',
                  label: `DAC overview`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/data-availability/dac-configuration-defaults',
                  label: `DAC defaults`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/data-availability/configure-dac',
                  label: `DAC how-to`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/data-availability/dac-das-operations',
                  label: `DAC/DAS operations`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/data-availability/das-rpc-method-reference',
                  label: `DAS RPC method reference`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/data-availability/deploy-das',
                  label: `Deploy DAS`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/data-availability/deploy-mirror-das',
                  label: `Deploy mirror DAS`,
                },
              ],
            },
            {
              type: 'category',
              label: 'Execution',
              collapsed: true,
              items: [
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/execution/smart-contract-size-limit',
                  label: `Smart contract size`,
                },
              ],
            },
            {
              type: 'category',
              label: 'Sequencing',
              collapsed: true,
              items: [
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/sequencer/chain-finality',
                  label: `Chain finality`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/sequencer/sequencer-timing-adjustments',
                  label: `Sequencer timing adjustments`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/sequencer/timeboost',
                  label: `Timeboost`,
                },
              ],
            },
            {
              type: 'category',
              label: 'Validation',
              collapsed: true,
              items: [
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/validation/assertion-control',
                  label: `Assertion control`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/validation/bold',
                  label: `BoLD`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/validation/bond-and-validator',
                  label: `Bond and validator`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/validation/challenge-period',
                  label: `Challenge period`,
                },
                {
                  type: 'doc',
                  id: 'launch-arbitrum-chain/chain-config/validation/fast-withdrawals',
                  label: `Fast withdrawals`,
                },
              ],
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/chain-config/additional-configuration-parameters',
              label: `Additional configuration parameters`,
            },
          ],
        },
        {
          type: 'category',
          label: 'Deployment',
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/deploy/canonical-factory-contracts',
              label: `Canonical factory contracts`,
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/deploy/configure-node',
              label: `Node configuration`,
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/deploy/deploy-chain',
              label: `Deploy`,
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/deploy/token-bridge',
              label: `Token bridge`,
            },
          ],
        },
        {
          type: 'category',
          label: 'Integrations',
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/integrations/bridge-ui',
              label: 'Bridge UI',
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/integrations/bridged-usdc',
              label: 'Bridged USDC',
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/integrations/infrastructure-providers',
              label: 'Infrastructure providers',
            },
          ],
        },
        {
          type: 'category',
          label: 'Migrate',
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/migrate/between-raases',
              label: `Between RaaSes`,
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/migrate/from-another-stack',
              label: `From another stack`,
            },
          ],
        },
        {
          type: 'category',
          label: 'Operate',
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/operate/arbos-upgrade',
              label: 'ArbOS upgrade',
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/operate/batch-poster-troubleshooting',
              label: 'Batch poster troubleshooting',
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/operate/key-rotation',
              label: 'Key rotation',
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/operate/monitoring',
              label: 'Monitoring',
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/operate/ownership-and-access',
              label: 'Ownership and access',
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/operate/post-launch-deployments',
              label: 'Post-launch deployments',
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/operate/state-growth',
              label: 'State growth',
            },
          ],
        },
        {
          type: 'category',
          label: 'Protocol hacks',
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/protocol-hacks/arbos',
              label: `ArbOS`,
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/protocol-hacks/da-api-guide',
              label: 'DA API guide',
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/protocol-hacks/precompiles',
              label: `Precompiles`,
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/protocol-hacks/stf',
              label: `State Transition Function`,
            },
          ],
        },
        {
          type: 'category',
          label: 'Run a node for an Arbitrum chain',
          collapsed: true,
          items: [
            {
              type: 'html',
              value:
                '<a class="menu__link menu__list-item" href="/run-arbitrum-node/run-full-node">Run a full node <span class="other-section-icon">↓</span></a>',
              // q: why use an anchor html tag here?
              // a: see note at end of file
            },
            {
              type: 'html',
              value:
                '<a class="menu__link menu__list-item" href="/run-arbitrum-node/more-types/run-validator-node">Run a validator <span class="other-section-icon">↓</span></a>',
              // q: why use an anchor html tag here?
              // a: see note at end of file
            },
            {
              type: 'html',
              value:
                '<a class="menu__link menu__list-item" href="/run-arbitrum-node/sequencer/run-sequencer-node">Run a sequencer node <span class="other-section-icon">↓</span></a>',
              // q: why use an anchor html tag here?
              // a: see note at end of file
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/run-a-node/batch-poster',
              label: 'Batch poster',
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/run-a-node/split-validator-node',
              label: 'Split validator node',
            },
            {
              type: 'doc',
              id: 'launch-arbitrum-chain/run-a-node/high-availability-sequencer',
              label: 'High availability sequencer',
            },
          ],
        },
      ],
    },

    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/for-devs/dev-tools-and-resources/chain-info">Chain Info<span class="other-section-icon">↑</span></a>',
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/intro/glossary">Glossary<span class="other-section-icon">↑</span></a>',
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/for-devs/contribute">Contribute<span class="other-section-icon">↑</span></a>',
    },
  ],

  // Run Node sidebar
  runNodeSidebar: [
    {
      type: 'category',
      label: 'Run an Arbitrum node',
      collapsed: false,
      link: {
        type: 'doc',
        id: 'run-arbitrum-node/overview',
      },
      items: [
        {
          type: 'doc',
          id: 'run-arbitrum-node/overview',
          label: 'Overview',
        },
        {
          type: 'doc',
          id: 'run-arbitrum-node/nitro-support-policy',
          label: 'Nitro support policy',
        },
        {
          type: 'doc',
          id: 'run-arbitrum-node/start-here',
          label: 'Start here',
        },
        {
          type: 'doc',
          id: 'run-arbitrum-node/run-full-node',
          label: 'Run a full node',
        },
        {
          type: 'doc',
          id: 'run-arbitrum-node/run-local-full-chain-simulation',
          label: 'Run a local full chain simulation',
        },
        {
          type: 'doc',
          id: 'run-arbitrum-node/run-nitro-dev-node',
          label: 'Run a local dev node',
        },
        {
          type: 'doc',
          id: 'run-arbitrum-node/l1-ethereum-beacon-chain-rpc-providers',
          label: 'L1 Ethereum RPC providers',
        },
        {
          type: 'doc',
          id: 'run-arbitrum-node/data-availability',
          label: 'Data Availability',
        },
        {
          type: 'doc',
          id: 'run-arbitrum-node/run-feed-relay',
          label: 'Run a feed relay',
        },
        {
          type: 'doc',
          id: 'run-arbitrum-node/beacon-nodes-historical-blobs',
          label: 'Historical blobs',
        },
        {
          type: 'category',
          label: 'ArbOS software releases',
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'run-arbitrum-node/arbos-releases/overview',
              label: 'Overview',
            },
            {
              type: 'doc',
              id: 'run-arbitrum-node/arbos-releases/arbos51',
              label: 'Dia (ArbOS 51)',
            },
            {
              type: 'doc',
              id: 'run-arbitrum-node/arbos-releases/arbos40',
              label: 'Callisto (ArbOS 40)',
            },
            {
              type: 'doc',
              id: 'run-arbitrum-node/arbos-releases/arbos32',
              label: 'Bianca (ArbOS 32)',
            },
            {
              type: 'doc',
              id: 'run-arbitrum-node/arbos-releases/arbos20',
              label: 'Atlas (ArbOS 20)',
            },
            {
              type: 'doc',
              id: 'run-arbitrum-node/arbos-releases/arbos11',
              label: 'ArbOS 11',
            },
          ],
        },
        {
          type: 'category',
          label: 'More node types',
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'run-arbitrum-node/more-types/run-archive-node',
              label: 'Run an archive node',
            },
            {
              type: 'doc',
              id: 'run-arbitrum-node/more-types/run-validator-node',
              label: 'Run a validator',
            },
            {
              type: 'doc',
              id: 'run-arbitrum-node/more-types/run-classic-node',
              label: 'Run a Classic node',
            },
          ],
        },
        {
          type: 'category',
          label: 'Sequencer',
          collapsed: true,
          items: [
            {
              type: 'doc',
              id: 'run-arbitrum-node/sequencer/run-sequencer-node',
              label: 'Run a sequencer node',
            },
            {
              type: 'doc',
              id: 'run-arbitrum-node/sequencer/read-sequencer-feed',
              label: 'Read the sequencer feed',
            },
            {
              type: 'doc',
              id: 'run-arbitrum-node/sequencer/run-sequencer-coordination-manager',
              label: 'Run a Sequencer Coordination Manager (SQM)',
            },
          ],
        },
        {
          type: 'doc',
          id: 'run-arbitrum-node/nitro/build-nitro-locally',
          label: 'Build Nitro locally',
        },
        {
          type: 'doc',
          id: 'run-arbitrum-node/nitro/migrate-state-and-history-from-classic',
          label: 'Migrate to Nitro from Classic',
        },
        {
          type: 'doc',
          id: 'run-arbitrum-node/nitro/nitro-database-snapshots',
          label: 'Database snapshots',
        },
        {
          type: 'doc',
          id: 'run-arbitrum-node/nitro/how-to-convert-databases-from-leveldb-to-pebble',
          label: 'Convert databases from LevelDB to Pebble',
        },
        {
          type: 'doc',
          id: 'run-arbitrum-node/nitro/configuration-system',
          label: 'Configuration system',
        },
        {
          type: 'doc',
          id: 'run-arbitrum-node/nitro/da-tools-reference',
          label: 'DA tools reference',
        },
        {
          type: 'doc',
          id: 'run-arbitrum-node/nitro/cli-flags-reference',
          label: 'CLI flags reference',
        },
        {
          type: 'doc',
          id: 'run-arbitrum-node/troubleshooting',
          label: 'Troubleshooting',
        },
        {
          type: 'doc',
          label: 'FAQ',
          id: 'node-running/faq',
        },
      ],
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/for-devs/dev-tools-and-resources/chain-info">Chain Info<span class="other-section-icon">↑</span></a>',
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/intro/glossary">Glossary<span class="other-section-icon">↑</span></a>',
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/for-devs/contribute">Contribute<span class="other-section-icon">↑</span></a>',
    },
  ],

  // Bridge sidebar
  bridgeSidebar: [
    {
      type: 'category',
      label: 'Arbitrum bridge',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'arbitrum-bridge/quickstart',
          label: 'Quickstart',
        },
        {
          type: 'doc',
          id: 'arbitrum-bridge/usdc-arbitrum-one',
          label: 'USDC on Arbitrum One',
        },
        {
          type: 'doc',
          id: 'arbitrum-bridge/embedded-bridge-widget',
          label: 'Embedded bridge widget',
        },
        {
          type: 'doc',
          id: 'arbitrum-bridge/bridge-transaction-traceability',
          label: 'Tracing bridge transactions',
        },
        {
          type: 'doc',
          id: 'arbitrum-bridge/troubleshooting',
          label: 'Troubleshooting',
        },
      ],
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/for-devs/dev-tools-and-resources/chain-info">Chain Info<span class="other-section-icon">↑</span></a>',
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/intro/glossary">Glossary<span class="other-section-icon">↑</span></a>',
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/for-devs/contribute">Contribute<span class="other-section-icon">↑</span></a>',
    },
  ],

  // How it Works sidebar
  howItWorksSidebar: [
    {
      type: 'category',
      label: 'How Arbitrum works',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'how-arbitrum-works/inside-arbitrum-nitro',
          label: 'Inside Arbitrum Nitro',
        },
        {
          type: 'html',
          value:
            '<a class="menu__link menu__list-item" href="/nitro-whitepaper.pdf">Nitro whitepaper<span class="other-section-icon">↑</span></a>',
        },
        {
          type: 'category',
          label: 'Deep dives',
          items: [
            {
              type: 'doc',
              label: 'AnyTrust',
              id: 'how-arbitrum-works/deep-dives/anytrust-protocol',
            },
            {
              type: 'doc',
              label: 'ArbOS',
              id: 'how-arbitrum-works/deep-dives/arbos',
            },
            {
              type: 'doc',
              label: 'Assertions',
              id: 'how-arbitrum-works/deep-dives/assertions',
            },
            {
              type: 'doc',
              label: 'Parent to Child chain Messaging',
              id: 'how-arbitrum-works/deep-dives/l1-to-l2-messaging',
            },
            {
              type: 'doc',
              label: 'Child to Parent chain Messaging',
              id: 'how-arbitrum-works/deep-dives/l2-to-l1-messaging',
            },
            {
              type: 'doc',
              label: 'Transaction lifecycle',
              id: 'how-arbitrum-works/deep-dives/transaction-lifecycle',
            },
            {
              type: 'doc',
              label: 'Gas and fees',
              id: 'how-arbitrum-works/deep-dives/gas-and-fees',
            },
            {
              type: 'doc',
              label: 'STF inputs',
              id: 'how-arbitrum-works/reference/stf-inputs',
            },
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          items: [
            {
              type: 'doc',
              label: 'Sequencer',
              id: 'how-arbitrum-works/deep-dives/sequencer',
            },
            {
              type: 'doc',
              label: 'Geth',
              id: 'how-arbitrum-works/reference/geth',
            },
          ],
        },
        {
          type: 'category',
          label: 'The BoLD dispute protocol',
          items: [
            {
              type: 'doc',
              id: 'how-arbitrum-works/bold/gentle-introduction',
              label: 'BoLD overview',
            },
            {
              type: 'link',
              href: 'https://github.com/offchainlabs/bold-validator-starter-kit',
              label: 'Deploy a validator on testnet',
            },
            {
              type: 'link',
              href: 'https://arxiv.org/abs/2404.10491',
              label: 'BoLD Whitepaper',
            },
            {
              type: 'doc',
              id: 'how-arbitrum-works/bold/bold-technical-deep-dive',
              label: 'Technical deep dive',
            },
            {
              type: 'doc',
              id: 'how-arbitrum-works/bold/bold-economics-of-disputes',
              label: 'Economics of disputes',
            },
            {
              type: 'link',
              href: 'https://github.com/OffchainLabs/bold',
              label: 'Specification on Github',
            },
            {
              type: 'link',
              href: 'https://github.com/trailofbits/publications/blob/master/reviews/2024-04-offchainbold-securityreview.pdf',
              label: 'Audit Report by Trail of Bits',
            },
            {
              type: 'link',
              href: 'https://code4rena.com/reports/2024-05-arbitrum-foundation',
              label: 'Audit Report by Code4rena',
            },
          ],
        },
        {
          type: 'category',
          label: 'Timeboost',
          items: [
            {
              type: 'doc',
              id: 'how-arbitrum-works/timeboost/gentle-introduction',
              label: 'How Timeboost works',
            },
            {
              type: 'doc',
              label: 'Use Timeboost',
              id: 'how-arbitrum-works/timeboost/how-to-use-timeboost',
            },
            {
              type: 'doc',
              label: 'Troubleshoot Timeboost',
              id: 'how-arbitrum-works/timeboost/troubleshoot-timeboost',
            },
            {
              type: 'doc',
              label: 'Timeboost FAQ',
              id: 'how-arbitrum-works/timeboost/timeboost-faq',
            },
            {
              type: 'link',
              href: 'https://github.com/OffchainLabs/timeboost-design/blob/main/research_spec.md',
              label: 'Specification: Timeboost',
            },
            {
              type: 'link',
              href: 'https://github.com/OffchainLabs/decentralized-timeboost-spec',
              label: 'Specification: Timeboost with decentralized sequencing',
            },
            {
              type: 'link',
              href: 'https://arxiv.org/abs/2306.02179',
              label: 'White paper: Timeboost',
            },
          ],
        },
      ],
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/for-devs/dev-tools-and-resources/chain-info">Chain Info<span class="other-section-icon">↑</span></a>',
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/intro/glossary">Glossary<span class="other-section-icon">↑</span></a>',
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/for-devs/contribute">Contribute<span class="other-section-icon">↑</span></a>',
    },
  ],

  // Unified build apps sidebar (combines build apps and Stylus)
  buildAppsSidebar: [
    {
      type: 'category',
      label: 'Build apps with Solidity',
      collapsed: false,
      items: [
        {
          type: 'doc',
          id: 'build-decentralized-apps/quickstart-solidity-remix',
          label: 'Quickstart',
        },
        {
          type: 'doc',
          id: 'build-decentralized-apps/quickstart-create-a-token',
          label: 'Create a token',
        },
        {
          type: 'ref',
          label: 'Solidity support',
          id: 'arbitrum-essentials/arbitrum-vs-ethereum/solidity-support',
        },
        {
          type: 'doc',
          label: 'Troubleshooting',
          id: 'for-devs/troubleshooting-building',
        },
        {
          type: 'category',
          label: 'Arbitrum essentials',
          collapsed: true,
          items: [
            {
              type: 'ref',
              label: 'Bridging',
              id: 'arbitrum-essentials/bridging/overview',
            },
            {
              type: 'ref',
              label: 'Oracles',
              id: 'arbitrum-essentials/oracles/overview-oracles',
            },
            {
              type: 'ref',
              label: 'Precompiles',
              id: 'arbitrum-essentials/precompiles/overview',
            },
            {
              type: 'ref',
              label: 'Estimate gas',
              id: 'arbitrum-essentials/how-to-estimate-gas',
            },
            {
              type: 'link',
              label: 'See all Arbitrum essentials →',
              href: '/arbitrum-essentials',
            },
          ],
        },
        {
          type: 'link',
          label: 'Arbitrum SDK',
          href: 'https://github.com/OffchainLabs/arbitrum-sdk',
        },
        {
          type: 'link',
          label: 'Example code repository',
          href: 'https://github.com/OffchainLabs/arbitrum-tutorials',
        },
      ],
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/for-devs/dev-tools-and-resources/chain-info">Chain Info<span class="other-section-icon">↑</span></a>',
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/intro/glossary">Glossary<span class="other-section-icon">↑</span></a>',
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/for-devs/contribute">Contribute<span class="other-section-icon">↑</span></a>',
    },
  ],

  // Language-neutral platform content, shared by both the Solidity and Stylus build tracks
  arbitrumEssentialsSidebar: [
    {
      type: 'category',
      label: 'Arbitrum essentials',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Arbitrum essentials',
        description:
          'Core, language-agnostic guidance for building on Arbitrum — bridging, oracles, precompiles, the NodeInterface, RPC and provider references, networks, gas, and how Arbitrum differs from Ethereum. Applies whether you write contracts in Solidity or Stylus.',
        slug: '/arbitrum-essentials',
      },
      items: [
        {
          type: 'doc',
          label: 'Estimate gas',
          id: 'arbitrum-essentials/how-to-estimate-gas',
        },
        {
          type: 'doc',
          label: 'Chains and testnets',
          id: 'arbitrum-essentials/public-chains',
        },
        {
          type: 'category',
          label: 'Bridging',
          collapsed: true,
          items: [
            {
              type: 'doc',
              label: 'Overview',
              id: 'arbitrum-essentials/bridging/overview',
            },
            {
              type: 'doc',
              label: 'Cross-chain messaging',
              id: 'arbitrum-essentials/bridging/cross-chain-messaging',
            },
            {
              type: 'doc',
              label: 'L1-to-L3 teleportation',
              id: 'arbitrum-essentials/bridging/l1-l3-teleportation',
            },
            {
              type: 'doc',
              label: 'Custom gas token chains',
              id: 'arbitrum-essentials/bridging/custom-gas-token-chains',
            },
            {
              type: 'category',
              label: 'Deposit (parent → child)',
              items: [
                {
                  type: 'doc',
                  label: 'ETH and messages',
                  id: 'arbitrum-essentials/bridging/deposit/eth-and-messages',
                },
                {
                  type: 'doc',
                  label: 'Tokens',
                  id: 'arbitrum-essentials/bridging/deposit/tokens',
                },
              ],
            },
            {
              type: 'category',
              label: 'Withdraw (child → parent)',
              items: [
                {
                  type: 'doc',
                  label: 'ETH and messages',
                  id: 'arbitrum-essentials/bridging/withdraw/eth-and-messages',
                },
                {
                  type: 'doc',
                  label: 'Tokens',
                  id: 'arbitrum-essentials/bridging/withdraw/tokens',
                },
              ],
            },
            {
              type: 'category',
              label: 'Configure token gateway',
              items: [
                {
                  type: 'doc',
                  label: 'Standard gateway',
                  id: 'arbitrum-essentials/bridging/configure-token-gateway/standard',
                },
                {
                  type: 'doc',
                  label: 'Generic-custom gateway',
                  id: 'arbitrum-essentials/bridging/configure-token-gateway/generic-custom',
                },
                {
                  type: 'doc',
                  label: 'Custom gateway',
                  id: 'arbitrum-essentials/bridging/configure-token-gateway/custom',
                },
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Arbitrum vs Ethereum',
          items: [
            {
              type: 'doc',
              label: 'Comparison overview',
              id: 'arbitrum-essentials/arbitrum-vs-ethereum/comparison-overview',
            },
            {
              type: 'doc',
              label: 'Block gas limit, numbers and time',
              id: 'arbitrum-essentials/arbitrum-vs-ethereum/block-numbers-and-time',
            },
            {
              type: 'doc',
              label: 'RPC methods',
              id: 'arbitrum-essentials/arbitrum-vs-ethereum/rpc-methods',
            },
            {
              type: 'doc',
              label: 'Solidity support',
              id: 'arbitrum-essentials/arbitrum-vs-ethereum/solidity-support',
            },
            {
              type: 'doc',
              label: 'Nonce management',
              id: 'arbitrum-essentials/arbitrum-vs-ethereum/nonce-management',
            },
          ],
        },
        {
          type: 'doc',
          label: 'Oracles',
          id: 'arbitrum-essentials/oracles/overview-oracles',
        },
        {
          type: 'category',
          label: 'Precompiles',
          collapsed: true,
          items: [
            {
              type: 'doc',
              label: 'Overview',
              id: 'arbitrum-essentials/precompiles/overview',
            },
            {
              type: 'doc',
              label: 'Reference',
              id: 'arbitrum-essentials/precompiles/reference',
            },
          ],
        },
        {
          type: 'category',
          label: 'NodeInterface',
          collapsed: true,
          items: [
            {
              type: 'doc',
              label: 'Overview',
              id: 'arbitrum-essentials/nodeinterface/overview',
            },
            {
              type: 'doc',
              label: 'Reference',
              id: 'arbitrum-essentials/nodeinterface/reference',
            },
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          items: [
            {
              type: 'doc',
              label: 'Chain parameters',
              id: 'arbitrum-essentials/reference/chain-params',
            },
            {
              type: 'doc',
              label: 'Contract addresses',
              id: 'arbitrum-essentials/reference/contract-addresses',
            },
            {
              type: 'doc',
              label: 'Debugging tools',
              id: 'arbitrum-essentials/reference/debugging-tools',
            },
            {
              type: 'doc',
              label: 'Development frameworks',
              id: 'arbitrum-essentials/reference/development-frameworks',
            },
            {
              type: 'doc',
              id: 'arbitrum-essentials/reference/mainnet-risks',
              label: 'Mainnet risks',
            },
            {
              type: 'doc',
              label: 'Monitoring tools and block explorers',
              id: 'arbitrum-essentials/reference/monitoring-tools-block-explorers',
            },
            {
              type: 'doc',
              id: 'arbitrum-essentials/reference/node-providers',
              label: 'RPC endpoints and providers',
            },
            {
              type: 'doc',
              label: 'Web3 libraries and tools',
              id: 'arbitrum-essentials/reference/web3-libraries-tools',
            },
          ],
        },
      ],
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/for-devs/dev-tools-and-resources/chain-info">Chain Info<span class="other-section-icon">↑</span></a>',
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/intro/glossary">Glossary<span class="other-section-icon">↑</span></a>',
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/for-devs/contribute">Contribute<span class="other-section-icon">↑</span></a>',
    },
  ],

  // Stylus-focused sidebar (only shows Stylus content)
  buildStylusSidebar: [
    {
      type: 'category',
      label: 'Build apps with Stylus',
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'Build apps with Stylus',
        description:
          "Learn how to build decentralized applications using Stylus, Arbitrum's next-generation smart contract platform supporting Rust, C, and C++.",
        slug: '/stylus',
      },
      items: [
        {
          type: 'doc',
          id: 'stylus/gentle-introduction',
          label: 'A gentle introduction',
        },
        {
          type: 'doc',
          id: 'stylus/quickstart',
          label: 'Quickstart',
        },
        {
          type: 'category',
          label: 'Fundamentals',
          items: [
            {
              type: 'doc',
              id: 'stylus/fundamentals/choose-your-path',
              label: 'Choose your path',
            },
            {
              type: 'doc',
              id: 'stylus/fundamentals/prerequisites',
              label: 'Prerequisites',
            },
            {
              type: 'doc',
              id: 'stylus/fundamentals/project-structure',
              label: 'Project structure',
            },
            {
              type: 'doc',
              id: 'stylus/fundamentals/contracts',
              label: 'Contract structure',
            },
            {
              type: 'doc',
              id: 'stylus/fundamentals/global-variables-and-functions',
              label: 'Global variables and functions',
            },
            {
              type: 'category',
              label: 'Data types',
              items: [
                {
                  type: 'doc',
                  id: 'stylus/fundamentals/data-types/primitives',
                  label: 'Primitives',
                },
                {
                  type: 'doc',
                  id: 'stylus/fundamentals/data-types/compound-types',
                  label: 'Compound types',
                },
                {
                  type: 'doc',
                  id: 'stylus/fundamentals/data-types/storage',
                  label: 'Storage',
                },
                {
                  type: 'doc',
                  id: 'stylus/fundamentals/data-types/conversions-between-types',
                  label: 'Conversions between types',
                },
              ],
            },
            {
              type: 'doc',
              id: 'stylus/fundamentals/testing-contracts',
              label: 'Testing contracts',
            },
          ],
        },
        {
          type: 'category',
          label: 'Guides',
          items: [
            {
              type: 'doc',
              id: 'stylus/how-tos/using-constructors',
              label: 'Using constructors',
            },
            {
              type: 'doc',
              id: 'stylus/how-tos/trait-based-composition',
              label: 'Composition, trait-based routing',
            },
            {
              type: 'doc',
              id: 'stylus/how-tos/importing-interfaces',
              label: 'Importing interfaces',
            },
            {
              type: 'doc',
              id: 'stylus/how-tos/exporting-abi',
              label: 'Exporting ABI',
            },
            {
              type: 'doc',
              id: 'stylus/how-tos/optimizing-binaries',
              label: 'Optimizing binaries',
            },
            {
              type: 'doc',
              id: 'stylus/how-tos/caching-contracts',
              label: 'Caching contracts',
            },
            {
              type: 'doc',
              id: 'stylus/how-tos/verifying-contracts-arbiscan',
              label: 'Verify contracts with Arbiscan',
            },
            {
              type: 'doc',
              id: 'stylus/how-tos/deploying-non-rust-wasm-contracts',
              label: 'Deploy non-Rust contracts',
            },
            {
              type: 'doc',
              id: 'stylus/how-tos/adding-support-for-new-languages',
              label: 'Add language support',
            },
          ],
        },
        {
          type: 'category',
          label: 'CLI tools',
          items: [
            {
              type: 'doc',
              id: 'stylus/cli-tools/overview',
              label: 'Overview',
            },
            {
              type: 'doc',
              id: 'stylus/cli-tools/check-and-deploy',
              label: 'Check and deploy',
            },
            {
              type: 'doc',
              id: 'stylus/cli-tools/verify-contracts',
              label: 'Verify contracts',
            },
            {
              type: 'doc',
              id: 'stylus/cli-tools/debugging-tx',
              label: 'Debugging transactions',
            },
            {
              type: 'doc',
              id: 'stylus/cli-tools/commands-reference',
              label: 'Commands reference',
            },
          ],
        },
        {
          type: 'category',
          label: 'Best Practices',
          collapsed: true,
          link: {
            type: 'generated-index',
          },
          items: [
            {
              type: 'doc',
              id: 'stylus/best-practices/security',
              label: 'Security',
            },
            {
              type: 'doc',
              id: 'stylus/best-practices/gas-optimization',
              label: 'Gas optimization',
            },
          ],
        },
        {
          type: 'category',
          label: 'Troubleshooting',
          collapsed: true,
          link: {
            type: 'generated-index',
          },
          items: [
            {
              type: 'doc',
              id: 'stylus/troubleshooting/common-issues',
              label: 'Common issues',
            },
          ],
        },
        {
          type: 'category',
          label: 'Concepts',
          items: [
            {
              type: 'doc',
              id: 'stylus/concepts/webassembly',
              label: 'WebAssembly',
            },
            {
              type: 'doc',
              id: 'stylus/concepts/activation',
              label: 'Activation',
            },
            {
              type: 'doc',
              id: 'stylus/concepts/gas-metering',
              label: 'Gas metering',
            },
            {
              type: 'doc',
              id: 'stylus/concepts/vm-differences',
              label: 'VM differences',
            },
            {
              type: 'doc',
              id: 'stylus/concepts/public-preview-expectations',
              label: 'Public preview expectations',
            },
          ],
        },
        {
          type: 'category',
          label: 'Advanced',
          items: [
            {
              type: 'doc',
              id: 'stylus/advanced/rust-to-solidity-differences',
              label: 'Rust to Solidity',
            },
            {
              type: 'doc',
              id: 'stylus/advanced/minimal-entrypoint-contracts',
              label: 'Minimal entrypoint contracts',
            },
            {
              type: 'doc',
              id: 'stylus/advanced/hostio-exports',
              label: 'Hostio exports',
            },
            {
              type: 'doc',
              id: 'stylus/advanced/recommended-libraries',
              label: 'Recommended libraries',
            },
          ],
        },
        {
          type: 'category',
          label: 'Reference',
          items: [
            {
              type: 'doc',
              id: 'stylus/reference/overview',
              label: 'Overview',
            },
            {
              type: 'doc',
              id: 'stylus/reference/opcode-hostio-pricing',
              label: 'Opcode and hostio pricing',
            },
            {
              type: 'doc',
              id: 'stylus/reference/stylus-toml-reference',
              label: 'Configuration reference',
            },
            {
              type: 'link',
              label: 'Stylus by Example',
              href: 'https://stylus-by-example.org/',
            },
            {
              type: 'link',
              label: 'Cargo Stylus CLI GitHub',
              href: 'https://github.com/OffchainLabs/stylus-sdk-rs/tree/main/cargo-stylus',
            },
            {
              type: 'link',
              label: 'Rust SDK Crate',
              href: 'https://docs.rs/stylus-sdk/latest/stylus_sdk/index.html',
            },
            {
              type: 'link',
              label: 'Source Code Repository',
              href: 'https://github.com/OffchainLabs/stylus-sdk-rs',
            },
          ],
        },
        {
          type: 'category',
          label: 'Arbitrum essentials',
          collapsed: true,
          items: [
            {
              type: 'ref',
              label: 'Bridging',
              id: 'arbitrum-essentials/bridging/overview',
            },
            {
              type: 'ref',
              label: 'Oracles',
              id: 'arbitrum-essentials/oracles/overview-oracles',
            },
            {
              type: 'ref',
              label: 'Precompiles',
              id: 'arbitrum-essentials/precompiles/overview',
            },
            {
              type: 'ref',
              label: 'Estimate gas',
              id: 'arbitrum-essentials/how-to-estimate-gas',
            },
            {
              type: 'link',
              label: 'See all Arbitrum essentials →',
              href: '/arbitrum-essentials',
            },
          ],
        },
        {
          type: 'doc',
          id: 'stylus/troubleshooting-building-stylus',
          label: 'FAQ',
        },
      ],
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/for-devs/dev-tools-and-resources/chain-info">Chain Info<span class="other-section-icon">↑</span></a>',
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/intro/glossary">Glossary<span class="other-section-icon">↑</span></a>',
    },
    {
      type: 'html',
      value:
        '<a class="menu__link menu__list-item" href="/for-devs/contribute">Contribute<span class="other-section-icon">↑</span></a>',
    },
  ],

  // Notices sidebar
  noticeSidebar: [
    {
      type: 'doc',
      id: 'notices/arbos60-upgrade-notice',
      label: 'Upgrade notice for ArbOS 60',
    },
    {
      type: 'doc',
      id: 'notices/arbos51-upgrade-notice',
      label: 'Upgrade notice for ArbOS 51',
    },
    {
      type: 'doc',
      id: 'notices/fusaka-upgrade-notice',
      label: 'Upgrade for the Fusaka transition',
    },
  ],
};

module.exports = sidebars;

// note RE html sidebar links:
//    because the linked page lives in multiple sidebar sections, we pick one to be the "canonical" location for the page in the sidebar
//    if we link to them both via id or standard href, multiple sections of the sidebar will be opened at once when the user visits this page; we don't want that
//    if we use a fully qualified link, the remote/published page will display when visiting from localhost or preview deployments
//    we also want to include a unicode arrow to indicate that we're routing the user to another section, in a way that's distinct from the icon that indicates "this href pulls you out of docs"
