<table>
  <thead>
    <tr>
      <th>Method</th>
      <th>Solidity interface</th>
      <th>Go implementation</th>
      <th>Description</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <code>getPricesInWeiWithAggregator(address aggregator)</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L22"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L26"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>GetPricesInWeiWithAggregator gets prices in wei when using the provided aggregator</td>
    </tr>
    <tr>
      <td>
        <code>getPricesInWei()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L44"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L101"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>GetPricesInWei gets prices in wei when using the caller's preferred aggregator</td>
    </tr>
    <tr>
      <td>
        <code>getPricesInArbGasWithAggregator(address aggregator)</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L58"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L106"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>
        GetPricesInArbGasWithAggregator gets prices in ArbGas when using the provided aggregator
      </td>
    </tr>
    <tr>
      <td>
        <code>getPricesInArbGas()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L69"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L158"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>GetPricesInArbGas gets prices in ArbGas when using the caller's preferred aggregator</td>
    </tr>
    <tr>
      <td>
        <code>getGasAccountingParams()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L80"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L163"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>GetGasAccountingParams gets the rollup's speed limit, pool size, and tx gas limit</td>
    </tr>
    <tr>
      <td>
        <code>getMinimumGasPrice()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L90"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L171"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>GetMinimumGasPrice gets the minimum gas price needed for a transaction to succeed</td>
    </tr>
    <tr>
      <td>
        <code>getL1BaseFeeEstimate()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L93"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L176"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>GetL1BaseFeeEstimate gets the current estimate of the L1 basefee</td>
    </tr>
    <tr>
      <td>
        <code>getL1BaseFeeEstimateInertia()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L96"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L181"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>
        GetL1BaseFeeEstimateInertia gets how slowly ArbOS updates its estimate of the L1 basefee
      </td>
    </tr>
    <tr>
      <td>
        <code>getL1RewardRate()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L100"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L186"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>GetL1RewardRate gets the L1 pricer reward rate</td>
    </tr>
    <tr>
      <td>
        <code>getL1RewardRecipient()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L104"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L191"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>GetL1RewardRecipient gets the L1 pricer reward recipient</td>
    </tr>
    <tr>
      <td>
        <code>getL1GasPriceEstimate()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L107"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L196"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>GetL1GasPriceEstimate gets the current estimate of the L1 basefee</td>
    </tr>
    <tr>
      <td>
        <code>getCurrentTxL1GasFees()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L110"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L201"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>GetCurrentTxL1GasFees gets the fee paid to the aggregator for posting this tx</td>
    </tr>
    <tr>
      <td>
        <code>getGasBacklog()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L113"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L206"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>GetGasBacklog gets the backlogged amount of gas burnt in excess of the speed limit</td>
    </tr>
    <tr>
      <td>
        <code>getPricingInertia()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L116"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L211"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>Returns how slowly ArbOS updates the L2 basefee in response to backlogged gas</td>
    </tr>
    <tr>
      <td>
        <code>getGasBacklogTolerance()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L119"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L216"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>
        GetGasBacklogTolerance gets the forgivable amount of backlogged gas ArbOS will ignore when
        raising the basefee
      </td>
    </tr>
    <tr>
      <td>
        <code>getL1PricingSurplus()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L122"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L221"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>Returns the surplus of funds for L1 batch posting payments (may be negative)</td>
    </tr>
    <tr>
      <td>
        <code>getPerBatchGasCharge()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L125"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L245"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>
        Returns the base charge (in L1 gas) attributed to each data batch in the calldata pricer
      </td>
    </tr>
    <tr>
      <td>
        <code>getAmortizedCostCapBips()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L128"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L250"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>Returns the cost amortization cap in basis points</td>
    </tr>
    <tr>
      <td>
        <code>getL1FeesAvailable()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L131"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L255"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>Returns the available funds from L1 fees</td>
    </tr>
    <tr>
      <td>
        <code>getL1PricingEquilibrationUnits()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L135"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L260"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>
        Returns the equilibration units parameter for L1 price adjustment algorithm (Available since
        ArbOS 20)
      </td>
    </tr>
    <tr>
      <td>
        <code>getLastL1PricingUpdateTime()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L139"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L265"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>Returns the last time the L1 calldata pricer was updated (Available since ArbOS 20)</td>
    </tr>
    <tr>
      <td>
        <code>getL1PricingFundsDueForRewards()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L143"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L270"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>
        Returns the amount of L1 calldata payments due for rewards (per the L1 reward rate)
        (Available since ArbOS 20)
      </td>
    </tr>
    <tr>
      <td>
        <code>getL1PricingUnitsSinceUpdate()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L147"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L275"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>
        Returns the amount of L1 calldata posted since the last update (Available since ArbOS 20)
      </td>
    </tr>
    <tr>
      <td>
        <code>getLastL1PricingSurplus()</code>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro-contracts/blob/7396313311ab17cb30e2eef27cccf96f0a9e8f7f/src/precompiles/ArbGasInfo.sol#L151"
          target="_blank"
        >
          Interface
        </a>
      </td>
      <td>
        <a
          href="https://github.com/OffchainLabs/nitro/blob/v3.2.1/precompiles/ArbGasInfo.go#L280"
          target="_blank"
        >
          Implementation
        </a>
      </td>
      <td>
        Returns the L1 pricing surplus as of the last update (may be negative) (Available since
        ArbOS 20)
      </td>
    </tr>
  </tbody>
</table>
