import { notFound } from 'next/navigation';

import {
  archiveMarkdownParams,
  getArchiveLLMText,
  getLLMText,
  getPageMarkdownUrl,
  resolveDocsPath,
  source,
} from '@/lib/source';

export const revalidate = false;
/**
 * Leave dynamic params enabled for the markdown mirror. Next 16 returns a 404 for proxy rewrites
 * from `/docs/x.md` and negotiated `/docs/x` onto this route when `dynamicParams` is false, even
 * when the destination was generated by `generateStaticParams`. Direct mirror requests work, but
 * the two public markdown shapes do not. `resolveDocsPath` still rejects unknown slugs and archive
 * versions with `notFound()`, and its version lookup guards prototype-named slugs.
 */
export async function GET(_req: Request, { params }: RouteContext<'/llms.mdx/docs/[[...slug]]'>) {
  const { slug } = await params;
  // Dynamic params are needed for proxy rewrites, so validate the filename that the static
  // parameter list otherwise constrained. `/llms.mdx/docs/x/anything` is not a mirror of `x`.
  if (slug?.at(-1) !== 'content.md') notFound();
  // Dropping the trailing `content.md` leaves the docs slug this mirror belongs to. For an archive
  // that slug still carries its version id, which is what `resolveDocsPath` reads: live page
  // first, so a real page can never be answered with somebody's archive.
  const resolved = resolveDocsPath(slug?.slice(0, -1));
  if (!resolved) notFound();

  const { page, archive } = resolved;

  return new Response(archive ? await getArchiveLLMText(page, archive) : await getLLMText(page), {
    headers: {
      'Content-Type': 'text/markdown',
      // This response also serves negotiated /docs URLs. Keep the variant marker on the
      // prerendered response itself so it survives Next's rewrite response handling.
      'Vary': 'Accept',
      // An archive's HTML carries `robots: { index: false, follow: true }` plus a canonical to the
      // live page (FS-2698: an outdated node-operator guide outranking the live one gets stale
      // operational instructions followed in production). A markdown body can hold neither tag, so
      // the same decision is stated in the only place a plain-text response has for it. Live pages
      // send no such header, exactly as before.
      ...(archive ? { 'X-Robots-Tag': 'noindex, follow' } : {}),
    },
  });
}

export function generateStaticParams() {
  return [
    ...source.getPages().map((page) => ({ slug: getPageMarkdownUrl(page).segments })),
    // Archived versions get the same three request shapes live pages have (FS-2711). Prerendering
    // them here is what puts `/docs/<slug>/<id>.md` and the negotiated archive URL on a built file
    // rather than a render per request, since both rewrite onto this route.
    ...archiveMarkdownParams(),
  ];
}
