/**
 * Shared helpers for the generated-content scripts (precompile tables, version pins).
 *
 * Centralizes the three things every generator needs: deterministic Prettier-formatted
 * output, a `--check` mode for drift detection, and uniform success/failure handling.
 *
 * Ported from arbitrum-docs `scripts/lib/generated-partial.ts`.
 */
import { createProcessor } from '@mdx-js/mdx';
import { remarkGfm } from 'fumadocs-core/mdx-plugins';
import fs from 'node:fs';
import path from 'node:path';
import prettier from 'prettier';
import type { Options as PrettierOptions } from 'prettier';
import remarkMath from 'remark-math';

/** Thrown by {@link writeOrCheck} in check mode when the on-disk file is stale. */
export class StaleFileError extends Error {
  /**
   * The Prettier-formatted text the generator would have written. Carried on the error so a
   * caller that wants to print a diff does not have to format the same content a second time to
   * get it.
   */
  readonly formatted: string | undefined;

  constructor(filePath: string, formatted?: string) {
    super(
      `${path.relative(process.cwd(), filePath)} is out of date. ` +
        `Run the generator without --check and commit the result.`,
    );
    this.name = 'StaleFileError';
    this.formatted = formatted;
  }
}

/** True when the script was invoked with a `--check` flag. */
export const isCheckMode = (): boolean => process.argv.includes('--check');

/**
 * Build the `{/* AUTOGENERATED *\/}` MDX comment every generated partial opens with, so a hand
 * edit is visibly wrong at the file itself and the generators that emit one cannot drift in
 * wording. Shared by `generate-contract-addresses.ts` and `generate-precompile-tables.ts`.
 *
 * Both arguments are spliced into an MDX expression comment unescaped, so each is rejected if it
 * carries a `*\/` (which would close the comment early and leak the remainder of the marker into
 * the page as body copy) or a newline (which would split one comment across two lines and leave
 * the second orphaned). Neither failure is visible in the generator's output, only on the rendered
 * page, so this throws at the call site instead: every caller builds its marker at module scope,
 * which makes a bad argument a loud import-time crash rather than a corrupted partial.
 *
 * @param command the pnpm script that regenerates the file, e.g. `pnpm contracts:generate`.
 * @param trigger what to run it after, with no leading "after" and no trailing period,
 *   e.g. `bumping @arbitrum/sdk or editing scripts/data/contract-addresses.data.ts`.
 * @throws when either argument contains `*\/` or a newline.
 */
export function generatedMarker(command: string, trigger: string): string {
  for (const [label, value] of [
    ['command', command],
    ['trigger', trigger],
  ]) {
    if (value.includes('*/')) {
      throw new Error(
        `generatedMarker: ${label} may not contain "*/", which would close the MDX comment ` +
          `early and leak the rest of the marker into the page: ${JSON.stringify(value)}`,
      );
    }
    if (/[\r\n]/.test(value)) {
      throw new Error(
        `generatedMarker: ${label} may not contain a newline, which would split the marker ` +
          `across two lines: ${JSON.stringify(value)}`,
      );
    }
  }

  return `{/* AUTOGENERATED. Do not edit by hand. Run \`${command}\` after ${trigger}. */}`;
}

/** Options for {@link writeOrCheck}. */
export interface WriteOrCheckOptions {
  /** Compare against the file on disk instead of writing it. */
  check: boolean;
  /** Merged over the resolved repo Prettier config. */
  overrides?: PrettierOptions;
  /** `false` skips Prettier and writes `content` byte for byte. */
  format?: boolean;
  /** Validate the final bytes before either writing or comparing them. */
  validate?: (formatted: string) => void;
}

/**
 * Format `content` with Prettier, then either write it (default) or, in check mode,
 * compare against the file on disk and throw {@link StaleFileError} if they differ.
 * Prettier is what makes check mode reliable: it turns the generator's loose template
 * whitespace into one canonical form.
 *
 * `overrides` is merged over the resolved repo config. Callers writing `.mdx` MUST pass
 * the generated-MDX options (see MDX_FORMAT in generate-precompile-tables.ts): repo-wide
 * Prettier deliberately skips `**\/*.mdx` via .prettierignore, which the programmatic API
 * does not honour, so a generator that inherited the default config would reformat MDX in
 * a way `pnpm format:check` never asked for.
 *
 * `format: false` skips Prettier entirely, for a file whose canonical shape is one Prettier
 * actively disagrees with. `meta.json` is the case that exists: `.prettierignore` excludes it
 * because `stringifyMeta` writes one array entry per line and Prettier collapses a short array,
 * so formatting it here would make the generator and `pnpm move-doc` undo each other on every
 * run. A caller passing `false` owns the exact bytes, trailing newline included.
 *
 * @returns true when the file was written and its content changed.
 */
export async function writeOrCheck(
  filePath: string,
  content: string,
  { check, overrides = {}, format = true, validate }: WriteOrCheckOptions,
): Promise<boolean> {
  const formatted = format
    ? await prettier.format(content, {
        ...(await prettier.resolveConfig(filePath)),
        filepath: filePath,
        ...overrides,
      })
    : content;
  validate?.(formatted);
  const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf-8') : '';

  if (check) {
    if (current !== formatted) throw new StaleFileError(filePath, formatted);
    return false;
  }

  if (current === formatted) return false;

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, formatted);
  console.log(`wrote ${path.relative(process.cwd(), filePath)}`);
  return true;
}

/**
 * Append a `name=value` pair to the GitHub Actions step-output file. No-op outside
 * Actions, where GITHUB_OUTPUT is unset, so local runs behave identically minus the
 * output plumbing.
 */
export function setOutput(name: string, value: string): void {
  // The file is line-oriented: a newline in either half would end this pair early and start a
  // second one of the value's choosing. Checked before the GITHUB_OUTPUT test so a local run
  // fails the same way CI would.
  for (const [label, text] of [
    ['name', name],
    ['value', value],
  ]) {
    if (/[\r\n]/.test(text)) {
      throw new Error(
        `setOutput: the ${label} of step output ${JSON.stringify(name)} may not contain a ` +
          `newline, which would inject a second output line: ${JSON.stringify(text)}`,
      );
    }
  }
  const outputFile = process.env.GITHUB_OUTPUT;
  if (!outputFile) return;
  fs.appendFileSync(outputFile, `${name}=${value}\n`);
}

/** Options for {@link assertInertMdx}. */
export interface InertMdxOptions {
  /** The file the text becomes, for the error message. */
  context: string;
  /**
   * JSX element names the generator writes itself. Each may carry only literal attributes; any
   * `{…}` attribute is rejected even on an allowed element. Anything not listed is rejected.
   */
  allowedElements: readonly string[];
  /** When provided for an element, require exactly these literal attributes and values. */
  allowedElementAttributes?: Readonly<Record<string, Readonly<Record<string, string | null>>>>;
  /**
   * When set, every allowed element must be written exactly as one of these strings (the whole
   * tag, source text). The generator's own `<include cwd>…</include>` is the case: `<include>`
   * reads and embeds any file the build machine can open, so the element name alone is no guard.
   */
  exactSources?: readonly string[];
  /** Added to every reported line, for text that sits below a stripped frontmatter block. */
  lineOffset?: number;
}

/** The mdast node types that carry JavaScript: `import`/`export` and `{…}` in flow or text. */
const CODE_NODE_TYPES = new Set(['mdxjsEsm', 'mdxFlowExpression', 'mdxTextExpression']);

/** The subset of an mdast node {@link assertInertMdx} reads. */
interface MdxNode {
  type: string;
  name?: string | null;
  value?: string;
  attributes?: Array<{ type: string; name?: string; value?: unknown }>;
  children?: MdxNode[];
  position?: { start: { line: number; offset: number }; end: { offset: number } };
  data?: { estree?: { body: unknown[] } };
}

/**
 * Throw unless `text` is MDX that compiles to static content: no `import` or `export`, no `{…}`
 * expression, and no JSX element or attribute the generator did not write itself.
 *
 * Every generated page or partial that copies upstream text into MDX calls this on its output,
 * because MDX is a program: an expression or an `export` in upstream text runs in the build, with
 * the build's environment, and again in every reader's browser. Escaping at the point of
 * interpolation is the first fence; this is the second, and the one that also covers text copied
 * whole (the Stylus page bodies) where there is nothing to escape.
 *
 * A comment-only expression, `{/* … *\/}`, is allowed: it compiles to nothing, and it is how the
 * generators write their do-not-edit markers. Fenced and inline code are not parsed as MDX, so
 * `{` and `<` inside them pass. Text the MDX parser rejects outright also throws here, naming the
 * same file, so a broken page fails the generator rather than the build.
 *
 * The parse uses the syntax extensions the build uses (GFM through the Fumadocs preset, maths
 * through `lib/mdx-options.ts`), because they move the boundaries of inline content: without GFM a
 * code span may run across a table row, and the `{…}` inside it would hide from this check and
 * run in the build.
 */
export function assertInertMdx(
  text: string,
  {
    context,
    allowedElements,
    allowedElementAttributes,
    exactSources,
    lineOffset = 0,
  }: InertMdxOptions,
): void {
  let tree: MdxNode;
  try {
    tree = createProcessor({ remarkPlugins: [remarkGfm, remarkMath] }).parse(
      text,
    ) as unknown as MdxNode;
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    throw new Error(`${context}: not valid MDX, so it would break the build: ${reason}`);
  }

  const allowed = new Set(allowedElements);
  const exact = exactSources === undefined ? undefined : new Set(exactSources);
  const problems: string[] = [];
  const visit = (node: MdxNode): void => {
    const line = (node.position?.start.line ?? 0) + lineOffset;
    if (CODE_NODE_TYPES.has(node.type)) {
      const commentOnly = node.type !== 'mdxjsEsm' && node.data?.estree?.body.length === 0;
      if (!commentOnly) {
        problems.push(`line ${line}: ${node.type} ${JSON.stringify(node.value ?? '')}`);
      }
    } else if (node.type === 'mdxJsxFlowElement' || node.type === 'mdxJsxTextElement') {
      const name = node.name ?? '<>';
      if (!allowed.has(name)) {
        problems.push(`line ${line}: JSX element <${name}>, which the generator does not write`);
      } else if (exact !== undefined && node.position !== undefined) {
        const written = text.slice(node.position.start.offset, node.position.end.offset);
        if (!exact.has(written)) {
          problems.push(
            `line ${line}: <${name}> written as ${JSON.stringify(written)}, which the generator ` +
              `does not write`,
          );
        }
      }
      for (const attribute of node.attributes ?? []) {
        const literal = attribute.value == null || typeof attribute.value === 'string';
        if (attribute.type !== 'mdxJsxAttribute' || !literal) {
          problems.push(
            `line ${line}: an expression attribute on <${name}>` +
              (attribute.name ? ` (${attribute.name})` : ''),
          );
        }
      }
      const expectedAttributes = allowedElementAttributes?.[name];
      if (expectedAttributes !== undefined) {
        const expected = Object.entries(expectedAttributes);
        const attributes = node.attributes ?? [];
        if (
          attributes.length !== expected.length ||
          !expected.every(([key, value]) => {
            const matching = attributes.filter((attribute) => attribute.name === key);
            return matching.length === 1 && matching[0].value === value;
          })
        ) {
          problems.push(
            `line ${line}: <${name}> must have exactly ${JSON.stringify(expectedAttributes)} literal attributes`,
          );
        }
      }
    }
    for (const child of node.children ?? []) visit(child);
  };
  visit(tree);

  if (problems.length > 0) {
    throw new Error(
      `${context}: the generated text would compile to code, not content. MDX runs ` +
        `\`import\`, \`export\`, \`{…}\` and JSX, in the build and in the browser, so the ` +
        `generator refuses to write it. Fix it where it came from (upstream, or a data file in ` +
        `this repo), or put it in a code fence there:\n` +
        problems.map((problem) => `  - ${problem}`).join('\n'),
    );
  }
}

/**
 * Read a file from an upstream checkout, refusing one reached through a symlink.
 *
 * `git clone` and `tar` both check a symlink out as a symlink, so an upstream file (or a directory
 * above it) could point at any file on the machine running the generator, and its text would be
 * read as if upstream had written it. `root` must be the materialized checkout root, not an
 * upstream-controlled subdirectory such as `src/app` or a module inside the checkout. System
 * aliases above that root (for example macOS's `/var`) are resolved before comparing paths.
 */
function assertPathInCheckout(file: string, root: string): fs.Stats {
  const relative = path.relative(root, file);
  if (relative === '..' || relative.startsWith(`..${path.sep}`) || path.isAbsolute(relative)) {
    throw new Error(`${file} is outside the upstream checkout ${root}.`);
  }
  if (fs.lstatSync(root).isSymbolicLink()) {
    throw new Error(`${root} is a symlink, not a materialized upstream checkout root.`);
  }
  const realRoot = fs.realpathSync(root);
  const expected = path.join(realRoot, relative);
  const stat = fs.lstatSync(file);
  if (stat.isSymbolicLink() || fs.realpathSync(file) !== expected) {
    throw new Error(
      `${relative || file} is a symlink, or sits under one, in the upstream tree. The ` +
        `generator reads only regular files, so a link cannot publish a file from outside the clone.`,
    );
  }
  return stat;
}

/** Validate a directory before traversing it, using the same checkout boundary as file reads. */
export function assertDirectoryInCheckout(dir: string, root: string): void {
  if (!assertPathInCheckout(dir, root).isDirectory()) {
    throw new Error(`${dir} is not a directory in the upstream checkout.`);
  }
}

/** Read a regular file, rejecting symlinks and paths outside the materialized checkout root. */
export function readRegularFile(file: string, root: string): string {
  if (!assertPathInCheckout(file, root).isFile()) {
    throw new Error(`${file} is not a regular file in the upstream checkout.`);
  }
  return fs.readFileSync(file, 'utf-8');
}

/**
 * Run a generator's `main` with uniform exit handling: a {@link StaleFileError} prints a
 * concise message, any other error prints in full, exit 0 on success and 1 on failure.
 */
export function runScript(main: () => Promise<void>): void {
  main()
    .then(() => process.exit(0))
    .catch((err: unknown) => {
      console.error(err instanceof StaleFileError ? err.message : err);
      process.exit(1);
    });
}
