/**
 * Tests for the shared generator helpers in `generated-partial.ts`. Among them is
 * `generatedMarker`, the shared do-not-edit comment both
 * `generate-contract-addresses.ts` and `generate-precompile-tables.ts` prepend to what they
 * write. Pinned here so the two generators cannot drift in wording, and so a change
 * to the shape is a deliberate, reviewed edit rather than something that slips in unnoticed.
 */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { describe, it } from 'node:test';

import {
  assertInertMdx,
  generatedMarker,
  readRegularFile,
  setOutput,
} from './generated-partial.ts';
import { NODE_INTERFACE_MARKER, PRECOMPILE_MARKER } from './precompile-tables.ts';

const PRECOMPILE_DIR = path.join('content', 'partials', 'precompile-tables');

/**
 * Fifteen precompiles plus `_NodeInterface.mdx`. Pinned so a partial going missing fails here
 * rather than shrinking the suite; adding a precompile is a deliberate edit to this number.
 */
const EXPECTED_PRECOMPILE_PARTIALS = 16;

describe('generatedMarker', () => {
  it('renders an MDX comment naming the regenerate command and the trigger', () => {
    assert.equal(
      generatedMarker('pnpm contracts:generate', 'bumping @arbitrum/sdk'),
      '{/* AUTOGENERATED. Do not edit by hand. Run `pnpm contracts:generate` after bumping @arbitrum/sdk. */}',
    );
  });

  it('rejects an argument containing `*/`, which would close the comment early', () => {
    // Left unchecked the marker would end at the caller's `*/` and leak its own tail into the
    // page as body copy. The generator's own output would look fine and only the rendered page
    // would show it, which is why this throws rather than escaping.
    assert.throws(() => generatedMarker('pnpm x:generate', 'editing a */ file'), /may not contain/);
    assert.throws(() => generatedMarker('pnpm */ generate', 'editing x'), /may not contain/);
  });

  it('rejects an argument containing a newline, which would split the marker in two', () => {
    assert.throws(() => generatedMarker('pnpm a\nb', 'c'), /may not contain a newline/);
    assert.throws(
      () => generatedMarker('pnpm x:generate', 'editing\nx'),
      /may not contain a newline/,
    );
  });

  it('starts with "{" so partial-catalog summary derivation skips it like it skips <table>', () => {
    // scripts/lib/partials.ts's deriveSummary skips lines starting with "{" or "<" while looking
    // for a partial's first sentence, so the marker must keep starting with "{" or every
    // generated partial's catalog summary would be the marker text. deriveTitle reaches the same
    // outcome by a different route: it inspects only the first non-blank line and falls back to
    // the humanized filename when that line is neither an ATX heading nor a titled Callout,
    // which is what `<table>` already did before the marker existed.
    assert.ok(generatedMarker('pnpm x:generate', 'editing x').startsWith('{'));
  });
});

/**
 * `generate-precompile-tables.ts` cannot be imported for a unit test: it calls `runScript(main)`
 * at module scope and every path to `writeOrCheck` runs through a `fetch` of a pinned GitHub
 * commit, so its only end-to-end guard is `precompiles:check`, which is network-bound and
 * run by hand. The parsing and rendering the generator delegates to is exercised
 * offline against fixture source in `scripts/lib/precompile-tables.test.ts`; that
 * proves the render step is correct, but says nothing about the 16 *committed* files in
 * `content/partials/precompile-tables/`, since a fixture is not that directory. This block is
 * what's left doing on-disk work, and it now asserts equality against the same `PRECOMPILE_MARKER`
 * / `NODE_INTERFACE_MARKER` constants the renderer uses, rather than a hand-copied regex, so the
 * two cannot disagree in wording. It still can't prove the generator produced these exact bytes
 * (that's `precompiles:check`, hand-run against the network), only that nobody hand-edited a
 * committed partial to drop the marker or that a partial didn't silently disappear.
 */
describe('generated precompile partials', () => {
  const files = fs.readdirSync(PRECOMPILE_DIR).filter((name) => name.endsWith('.mdx'));

  it(`finds all ${EXPECTED_PRECOMPILE_PARTIALS} partials`, () => {
    assert.equal(
      files.length,
      EXPECTED_PRECOMPILE_PARTIALS,
      `unexpected partial set in ${PRECOMPILE_DIR}`,
    );
  });

  for (const name of files) {
    const expectedMarker =
      name === '_NodeInterface.mdx' ? NODE_INTERFACE_MARKER : PRECOMPILE_MARKER;

    it(`${name} opens with the do-not-edit marker`, () => {
      const [first, second] = fs.readFileSync(path.join(PRECOMPILE_DIR, name), 'utf-8').split('\n');
      assert.equal(first, expectedMarker);
      assert.equal(second, '', 'the marker must be followed by a blank line');
    });
  }
});

describe('setOutput', () => {
  const withOutputFile = (fn: (file: string) => void): void => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'set-output-'));
    const file = path.join(dir, 'outputs');
    const previous = process.env.GITHUB_OUTPUT;
    process.env.GITHUB_OUTPUT = file;
    try {
      fn(file);
    } finally {
      if (previous === undefined) delete process.env.GITHUB_OUTPUT;
      else process.env.GITHUB_OUTPUT = previous;
      fs.rmSync(dir, { recursive: true, force: true });
    }
  };

  it('appends one name=value line', () => {
    withOutputFile((file) => {
      setOutput('newer_release', 'v3.11.5');
      assert.equal(fs.readFileSync(file, 'utf-8'), 'newer_release=v3.11.5\n');
    });
  });

  for (const value of ['v1.2.3\nupdates_made=true', 'v1.2.3\rx', '\n']) {
    it(`refuses a value holding a line break (${JSON.stringify(value)}) and writes nothing`, () => {
      withOutputFile((file) => {
        assert.throws(() => setOutput('newer_release', value), /may not contain a newline/);
        assert.equal(fs.existsSync(file), false);
      });
    });
  }

  it('refuses a name holding a line break', () => {
    withOutputFile(() => {
      assert.throws(() => setOutput('a\nb', 'x'), /the name of step output/);
    });
  });

  it('refuses a line break even outside Actions, so a local run fails the way CI would', () => {
    const previous = process.env.GITHUB_OUTPUT;
    delete process.env.GITHUB_OUTPUT;
    try {
      assert.throws(() => setOutput('x', 'a\nb'), /may not contain a newline/);
    } finally {
      if (previous !== undefined) process.env.GITHUB_OUTPUT = previous;
    }
  });
});

describe('assertInertMdx', () => {
  const check = (text: string, allowedElements: readonly string[] = []) =>
    assertInertMdx(text, { context: 'fixture.mdx', allowedElements });

  it('passes markdown, comment-only expressions and code holding braces and tags', () => {
    check(
      '{/* AUTOGENERATED */}\n\n# Title\n\nText {/* note */} with `{x} <T>`.\n\n' +
        '```rust\nfn f<T>() { let x = {1}; }\n```\n',
    );
  });

  it('passes an allowed element with literal and boolean attributes', () => {
    check('<include cwd>content/partials/_x.mdx</include>\n', ['include']);
    check('<a href="https://example.com" target="_blank">x</a>\n', ['a']);
  });

  for (const [label, text, pattern] of [
    ['an export', 'export const leak = process.env\n', /line 1: mdxjsEsm/],
    ['an import', "import x from 'y'\n", /line 1: mdxjsEsm/],
    ['a flow expression', '# T\n\n{globalThis.x = 1}\n', /line 3: mdxFlowExpression/],
    ['a text expression', 'Text {globalThis.x = 1} here\n', /line 1: mdxTextExpression/],
    ['an unlisted component', '<Script>x</Script>\n', /JSX element <Script>/],
    ['a fragment', '<>x</>\n', /JSX element <<>>/],
  ] as const) {
    it(`rejects ${label}, naming the file and line`, () => {
      assert.throws(
        () => check(text),
        (error: Error) => error.message.startsWith('fixture.mdx: ') && pattern.test(error.message),
      );
    });
  }

  it('rejects an expression attribute even on an allowed element', () => {
    assert.throws(
      () => check('<a href={x}>y</a>\n', ['a']),
      /expression attribute on <a> \(href\)/,
    );
    assert.throws(() => check('<a {...x}>y</a>\n', ['a']), /expression attribute on <a>/);
  });

  it('adds the line offset, for text below a stripped frontmatter block', () => {
    assert.throws(
      () => assertInertMdx('{x}\n', { context: 'f', allowedElements: [], lineOffset: 7 }),
      /line 8: mdxFlowExpression/,
    );
  });

  it('turns an MDX parse error into one naming the file', () => {
    assert.throws(() => check('returns x if a<b\n'), /^Error: fixture\.mdx: not valid MDX/);
  });
});

describe('readRegularFile', () => {
  it('reads a regular file and refuses a symlinked file or directory', (t) => {
    const root = fs.mkdtempSync(path.join(os.tmpdir(), 'read-regular-'));
    t.after(() => fs.rmSync(root, { recursive: true, force: true }));
    const outside = fs.mkdtempSync(path.join(os.tmpdir(), 'read-regular-outside-'));
    t.after(() => fs.rmSync(outside, { recursive: true, force: true }));
    fs.writeFileSync(path.join(outside, 'secret'), 'SECRET');
    fs.mkdirSync(path.join(root, 'real'));
    fs.writeFileSync(path.join(root, 'real', 'page.mdx'), 'ok');
    fs.symlinkSync(path.join(outside, 'secret'), path.join(root, 'real', 'linked.mdx'));
    fs.symlinkSync(outside, path.join(root, 'linked-dir'));

    assert.equal(readRegularFile(path.join(root, 'real', 'page.mdx'), root), 'ok');
    assert.throws(
      () => readRegularFile(path.join(root, 'real', 'linked.mdx'), root),
      /real\/linked\.mdx is a symlink/,
    );
    assert.throws(
      () => readRegularFile(path.join(root, 'linked-dir', 'secret'), root),
      /linked-dir\/secret is a symlink, or sits under one/,
    );
  });
});
