/**
 * Tests for `generatedMarker`, the shared do-not-edit comment both
 * `generate-contract-addresses.ts` and `generate-precompile-tables.ts` prepend to what they
 * write. Pinned here so the two generators cannot drift in wording (FS-2728), and so a change
 * to the shape is a deliberate, reviewed edit rather than something that slips in unnoticed.
 */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { describe, it } from 'node:test';

import { generatedMarker } from './generated-partial.ts';
import { NODE_INTERFACE_MARKER, PRECOMPILE_MARKER } from './precompile-tables.ts';

const PRECOMPILE_DIR = path.join('content', 'partials', 'precompile-tables');

/**
 * Fifteen precompiles plus `_NodeInterface.mdx`. Pinned so a partial going missing fails here
 * rather than shrinking the suite; adding a precompile is a deliberate edit to this number.
 */
const EXPECTED_PRECOMPILE_PARTIALS = 16;

describe('generatedMarker', () => {
  it('renders an MDX comment naming the regenerate command and the trigger', () => {
    assert.equal(
      generatedMarker('pnpm contracts:generate', 'bumping @arbitrum/sdk'),
      '{/* AUTOGENERATED. Do not edit by hand. Run `pnpm contracts:generate` after bumping @arbitrum/sdk. */}',
    );
  });

  it('rejects an argument containing `*/`, which would close the comment early', () => {
    // Left unchecked the marker would end at the caller's `*/` and leak its own tail into the
    // page as body copy. The generator's own output would look fine and only the rendered page
    // would show it, which is why this throws rather than escaping.
    assert.throws(() => generatedMarker('pnpm x:generate', 'editing a */ file'), /may not contain/);
    assert.throws(() => generatedMarker('pnpm */ generate', 'editing x'), /may not contain/);
  });

  it('rejects an argument containing a newline, which would split the marker in two', () => {
    assert.throws(() => generatedMarker('pnpm a\nb', 'c'), /may not contain a newline/);
    assert.throws(
      () => generatedMarker('pnpm x:generate', 'editing\nx'),
      /may not contain a newline/,
    );
  });

  it('starts with "{" so partial-catalog summary derivation skips it like it skips <table>', () => {
    // scripts/lib/partials.ts's deriveSummary skips lines starting with "{" or "<" while looking
    // for a partial's first sentence, so the marker must keep starting with "{" or every
    // generated partial's catalog summary would be the marker text. deriveTitle reaches the same
    // outcome by a different route: it inspects only the first non-blank line and falls back to
    // the humanized filename when that line is neither an ATX heading nor a VanillaAdmonition,
    // which is what `<table>` already did before the marker existed.
    assert.ok(generatedMarker('pnpm x:generate', 'editing x').startsWith('{'));
  });
});

/**
 * `generate-precompile-tables.ts` cannot be imported for a unit test: it calls `runScript(main)`
 * at module scope and every path to `writeOrCheck` runs through a `fetch` of a pinned GitHub
 * commit, so its only end-to-end guard is `precompiles:check`, which is network-bound and
 * `continue-on-error` in CI. The parsing and rendering the generator delegates to is exercised
 * offline against fixture source in `scripts/lib/precompile-tables.test.ts` (FS-2730); that
 * proves the render step is correct, but says nothing about the 16 *committed* files in
 * `content/partials/precompile-tables/`, since a fixture is not that directory. This block is
 * what's left doing on-disk work, and it now asserts equality against the same `PRECOMPILE_MARKER`
 * / `NODE_INTERFACE_MARKER` constants the renderer uses, rather than a hand-copied regex, so the
 * two cannot disagree in wording. It still can't prove the generator produced these exact bytes
 * (that's `precompiles:check`, hand-run against the network), only that nobody hand-edited a
 * committed partial to drop the marker or that a partial didn't silently disappear.
 */
describe('generated precompile partials', () => {
  const files = fs.readdirSync(PRECOMPILE_DIR).filter((name) => name.endsWith('.mdx'));

  it(`finds all ${EXPECTED_PRECOMPILE_PARTIALS} partials`, () => {
    assert.equal(
      files.length,
      EXPECTED_PRECOMPILE_PARTIALS,
      `unexpected partial set in ${PRECOMPILE_DIR}`,
    );
  });

  for (const name of files) {
    const expectedMarker =
      name === '_NodeInterface.mdx' ? NODE_INTERFACE_MARKER : PRECOMPILE_MARKER;

    it(`${name} opens with the do-not-edit marker`, () => {
      const [first, second] = fs.readFileSync(path.join(PRECOMPILE_DIR, name), 'utf-8').split('\n');
      assert.equal(first, expectedMarker);
      assert.equal(second, '', 'the marker must be followed by a blank line');
    });
  }
});
