/**
 * generate-stylus-examples: regenerate content/docs/stylus/stylus-by-example/ from
 * `offchainlabs/stylus-by-example`.
 *
 * Usage:
 *   pnpm stylus:generate                            # clone the upstream repo and write the pages
 *   pnpm stylus:generate --source-path ../sbe       # read an existing clone instead
 *   pnpm stylus:check                               # exit 1 with a diff summary when stale
 *
 * `--source-path` also reads from `STYLUS_REPO_PATH`; the flag wins when both are set. Either
 * way the pages come from the commit pinned as `repoRef` in `scripts/data/stylus-examples.data.ts`,
 * so a local clone must contain that commit.
 *
 * Without it, an edit to `offchainlabs/stylus-by-example` never reaches this site. An upstream
 * edit reaches it only when somebody bumps `repoRef`: stylus-by-example publishes no releases, so
 * the pin is a commit SHA. `--check` still needs the network (or `--source-path`), so it is not a
 * CI gate. Run it by hand.
 *
 * Each built page is checked before it is written: a body holding an `import`, `export`, `{…}`
 * expression or JSX the generator did not write fails the run (`assertStaticBody`), because the
 * build compiles and runs MDX. A symlinked page is refused too, since `git clone` checks symlinks
 * out as symlinks and one could point anywhere on the machine running the generator.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type { Options as PrettierOptions } from 'prettier';

import {
  frontmatterDefaults,
  notForProductionInclude,
  outputDir,
  outputUrl,
  repoRef,
  repoUrl,
  sections,
  sourceRoot,
} from './data/stylus-examples.data.ts';
import { stringifyMeta } from './lib/doc-links.ts';
import {
  StaleFileError,
  type WriteOrCheckOptions,
  isCheckMode,
  readRegularFile,
  runScript,
  writeOrCheck,
} from './lib/generated-partial.ts';
import { diffSummary } from './lib/line-diff.ts';
import { buildPage, buildSectionMeta } from './lib/stylus-examples.ts';

/** See MDX_FORMAT in generate-precompile-tables.ts: the generator owns these files' shape. */
const MDX_FORMAT: PrettierOptions = {
  parser: 'mdx',
  printWidth: 9999,
  proseWrap: 'preserve',
  plugins: [],
};

/** The comment that tells a human editing one of these pages that they are editing the wrong file. */
const MARKER =
  '{/* AUTOGENERATED. Do not edit by hand. Run `pnpm stylus:generate`. Source: ' +
  'https://github.com/offchainlabs/stylus-by-example */}';

interface Args {
  check: boolean;
  sourcePath: string | null;
}

function parseArgs(argv: string[]): Args {
  const args: Args = { check: isCheckMode(), sourcePath: process.env.STYLUS_REPO_PATH ?? null };
  for (let i = 0; i < argv.length; i++) {
    const value = argv[i + 1];
    if (argv[i] === '--source-path' && value) {
      args.sourcePath = value;
      i++;
    }
  }
  return args;
}

/**
 * Put the upstream tree under `workDir` and return the directory holding the app-router pages.
 *
 * A local clone is read through `git archive`, not off the working tree, so a checkout with local
 * edits or a stale index cannot leak into the generated pages, the same rule
 * `generate-cli-reference.ts` applies to Nitro.
 */
function materializeSource({
  sourcePath,
  workDir,
}: {
  sourcePath: string | null;
  workDir: string;
}): string {
  const treeDir = path.join(workDir, 'stylus-by-example');
  if (!/^[0-9a-f]{40}$/.test(repoRef)) {
    throw new Error(
      `repoRef in scripts/data/stylus-examples.data.ts must be a full 40-character commit SHA, ` +
        `not a branch or tag: ${JSON.stringify(repoRef)}`,
    );
  }

  if (sourcePath) {
    const repo = path.resolve(sourcePath);
    fs.mkdirSync(treeDir, { recursive: true });
    let archive: Buffer;
    try {
      archive = execFileSync('git', ['archive', `${repoRef}^{commit}`], {
        cwd: repo,
        maxBuffer: 256 * 1024 * 1024,
        stdio: ['ignore', 'pipe', 'pipe'],
      });
    } catch {
      throw new Error(
        `${repo} does not contain the pinned commit ${repoRef}. Run \`git fetch origin\` there, ` +
          `or bump repoRef in scripts/data/stylus-examples.data.ts to the commit you mean.`,
      );
    }
    execFileSync('tar', ['-x', '-C', treeDir], { input: archive, maxBuffer: 256 * 1024 * 1024 });
  } else {
    // `git clone --branch` takes only branch and tag names, so fetch the one commit by SHA
    // (GitHub serves any reachable commit this way) and check it out detached.
    console.log(`fetching ${repoUrl} at ${repoRef} (shallow)`);
    const git = (args: string[]) =>
      execFileSync('git', args, { cwd: treeDir, encoding: 'utf-8' }).trim();
    fs.mkdirSync(treeDir, { recursive: true });
    git(['init', '--quiet']);
    git(['fetch', '--depth', '1', '--quiet', repoUrl, repoRef]);
    git(['checkout', '--quiet', '--detach', 'FETCH_HEAD']);
    const head = git(['rev-parse', 'HEAD']);
    if (head !== repoRef) {
      throw new Error(`fetched ${head} from ${repoUrl}, expected the pinned ${repoRef}`);
    }
  }

  const appDir = path.join(treeDir, sourceRoot);
  if (!fs.existsSync(appDir)) {
    throw new Error(
      `${path.join(sourcePath ?? repoUrl, sourceRoot)} does not exist; the upstream repository ` +
        `has been restructured and scripts/data/stylus-examples.data.ts needs sourceRoot updated`,
    );
  }
  return appDir;
}

/**
 * Name the upstream examples this site does not publish.
 *
 * The allowlist is the reason the published set is stable, and also the reason an example added
 * upstream would otherwise be invisible here forever. Reporting is the whole job: nothing is
 * generated for these, and the run's log is where somebody notices one worth porting.
 */
function reportUnpublished(appDir: string): void {
  for (const section of sections) {
    const dir = path.join(appDir, section.dir);
    if (!fs.existsSync(dir)) continue;
    const upstream = fs
      .readdirSync(dir, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .filter((name) => fs.existsSync(path.join(dir, name, 'page.mdx')));

    const unpublished = upstream.filter((name) => !section.pages.includes(name));
    if (unpublished.length > 0) {
      console.log(
        `  ${section.dir}: ${unpublished.length} upstream example(s) not published here: ` +
          unpublished.join(', '),
      );
    }
  }
}

/**
 * Write (or check) one file, printing the line diff before rethrowing a staleness error.
 *
 * Every generator in this repo does this, for the same reason: "the file is stale" does not tell
 * a reviewer whether a code sample changed or only whitespace did.
 */
async function emit(
  filePath: string,
  content: string,
  options: WriteOrCheckOptions,
): Promise<boolean> {
  try {
    return await writeOrCheck(filePath, content, options);
  } catch (error) {
    // `formatted` is optional on the error's type but always set in check mode, the only mode
    // that throws it.
    if (error instanceof StaleFileError && error.formatted !== undefined) {
      const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf-8') : '';
      console.error(`${path.relative(process.cwd(), filePath)}:`);
      console.error(diffSummary(current, error.formatted));
    }
    throw error;
  }
}

async function main(): Promise<void> {
  const { check, sourcePath } = parseArgs(process.argv.slice(2));
  const workDir = fs.mkdtempSync(path.join(os.tmpdir(), 'stylus-by-example-'));

  let written = 0;
  let missingBanner: string[] = [];
  try {
    const appDir = materializeSource({ sourcePath, workDir });

    // A report, not a failure, and printed before the writes so it survives a staleness throw:
    // this is how an example added upstream gets noticed at all.
    reportUnpublished(appDir);

    for (const section of sections) {
      for (const slug of section.pages) {
        const context = path.join(sourceRoot, section.dir, slug, 'page.mdx');
        const sourceFile = path.join(appDir, section.dir, slug, 'page.mdx');
        if (!fs.existsSync(sourceFile)) {
          throw new Error(
            `${context} is gone from upstream. Either it was renamed, in which case update ` +
              `scripts/data/stylus-examples.data.ts and add a redirect, or it was deleted, in ` +
              `which case drop it from that file and from the page that links to it.`,
          );
        }

        const { content, banner } = buildPage({
          source: readRegularFile(sourceFile, appDir),
          context,
          marker: MARKER,
          frontmatterDefaults,
          sections,
          baseUrl: outputUrl,
          include: notForProductionInclude,
        });
        if (!banner) missingBanner.push(context);

        const target = path.join(outputDir, section.dir, `${slug}.mdx`);
        if (await emit(target, content, { check, overrides: MDX_FORMAT })) written++;
      }

      const metaPath = path.join(outputDir, section.dir, 'meta.json');
      // Not Prettier-formatted: see the `format: false` note on writeOrCheck. `stringifyMeta`
      // is the same writer `pnpm move-doc` uses, so the two agree on this file's shape.
      const meta = stringifyMeta(buildSectionMeta(section));
      if (await emit(metaPath, meta, { check, format: false })) written++;
    }
  } finally {
    fs.rmSync(workDir, { recursive: true, force: true });
  }

  const pages = sections.reduce((total, section) => total + section.pages.length, 0);
  console.log(
    check
      ? `stylus by example: up to date (${pages} page(s)).`
      : `stylus by example: ${pages} page(s) read, ${written} file(s) written.`,
  );

  // A report rather than a failure: a page loses its not-for-production banner when upstream
  // rewrites its first snippet in another language, which is a content decision, not a bug here.
  if (missingBanner.length > 0) {
    console.warn(
      `warning: no \`\`\`rust block, so no not-for-production banner, in:\n` +
        missingBanner.map((c) => `  - ${c}`).join('\n'),
    );
  }
}

runScript(main);
