/**
 * Tests for the Stylus-by-Example page transform.
 *
 * The fixture is a miniature `page.mdx` written inline, not a copy of an upstream example, so a
 * regression shows up as a named failing case rather than as a diff in nineteen generated pages
 * nobody reads line by line. Nothing here imports the runner, which would drag a network clone
 * and a repo-root cwd into the suite; the runner is wiring over the functions tested below.
 *
 * The data file is asserted against the committed tree instead: the allowlist doubles as the
 * `meta.json` order, so an entry that rots into a page nobody publishes would otherwise only
 * surface as a failed weekly refresh.
 */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { describe, it } from 'node:test';

import { outputDir, sections } from './data/stylus-examples.data.ts';
import {
  buildPage,
  buildSectionMeta,
  insertNotForProductionBanner,
  parseMetadata,
  parseObjectLiteral,
  renderFrontmatter,
  rewriteRelativeLinks,
  yamlScalar,
} from './lib/stylus-examples.ts';

const SOURCE = `export const metadata = {
  title: 'Hello World • Stylus by Example',
  description:
    'Prints output to the terminal using the \`console!\` macro.',
};

{/* Begin Content */}

# Hello World

Prose before the snippet, and a link to [ABI Encode](./abi_encode).

### Examples

\`\`\`rust
console!("hello there!");
\`\`\`
`;

const SECTIONS = [
  { dir: 'basic_examples', pages: ['abi_encode', 'hello_world'] },
  { dir: 'applications', pages: ['erc20'] },
];

const DEFAULTS = { content_type: 'concept', author: 'gblanchemain', sme: 'gblanchemain' };
const INCLUDE = '<include cwd>content/partials/_not-for-production-banner-partial.mdx</include>';

const build = (source = SOURCE) =>
  buildPage({
    source,
    context: 'src/app/basic_examples/hello_world/page.mdx',
    marker: '{/* AUTOGENERATED. */}',
    frontmatterDefaults: DEFAULTS,
    sections: SECTIONS,
    baseUrl: '/docs/stylus/stylus-by-example',
    include: INCLUDE,
  });

describe('parseMetadata', () => {
  it('reads the title and description off the Next.js metadata export', () => {
    const metadata = parseMetadata(SOURCE, 'fixture');
    assert.equal(metadata.title, 'Hello World • Stylus by Example');
    assert.match(metadata.description, /^Prints output to the terminal/);
  });

  it('throws when the page has no metadata export', () => {
    assert.throws(
      () => parseMetadata('# Just a heading\n', 'fixture'),
      /no `export const metadata`/,
    );
  });

  it('throws when a required field is missing, rather than emitting empty frontmatter', () => {
    // An empty `description` passes YAML and fails the Zod schema in source.config.ts, which
    // would surface as a build error on a page this generator wrote, far from the cause.
    const source = `export const metadata = { title: 'T' };\n`;
    assert.throws(() => parseMetadata(source, 'fixture'), /metadata\.description is missing/);
  });

  it('reads a block written the way upstream actually writes them', () => {
    // Every shape present across the 36 `metadata` blocks in stylus-by-example at 4bd4fb0:
    // double-quoted values beside single-quoted ones in the same block, the value wrapped onto
    // the line below its key, a trailing comma, an apostrophe inside a double-quoted string, and
    // a backtick and a `•` inside a single-quoted one. No block uses any escape sequence at all.
    const source = `export const metadata = {
  title: 'Bytes In, Bytes Out • Stylus by Example',
  description:
    "How to use Arbitrum's \`entrypoint\` function.",
};

# Heading
`;
    assert.deepEqual(parseMetadata(source, 'fixture'), {
      title: 'Bytes In, Bytes Out • Stylus by Example',
      description: "How to use Arbitrum's `entrypoint` function.",
    });
  });

  it('reads a block with no indentation at all', () => {
    // basic_examples/constructor/page.mdx upstream is written flush to the left margin.
    const source = `export const metadata = {\ntitle: "Constructors",\ndescription:\n"How to define them.",\n};\n`;
    assert.deepEqual(parseMetadata(source, 'fixture'), {
      title: 'Constructors',
      description: 'How to define them.',
    });
  });

  it('normalizes a doubled space or leading/trailing whitespace in title or description (FS-2747)', () => {
    // The upstream string basic_examples/variables/page.mdx actually ships (as of stylus-by-example
    // 4bd4fb0): a doubled space baked into the literal. Not a line-wrap artifact from this
    // generator, a real double space in upstream's own source string. Collapsed here so
    // `content:lint` rule A14 stays clean across a regeneration instead of needing a hand-edit the
    // next weekly `stylus` job would overwrite.
    const source = `export const metadata = {
  title: '  Padded  Title  ',
  description: 'Two  spaces mid-sentence and trailing space ',
};
`;
    assert.deepEqual(parseMetadata(source, 'fixture'), {
      title: 'Padded Title',
      description: 'Two spaces mid-sentence and trailing space',
    });
  });
});

describe('parseObjectLiteral', () => {
  it('reads the grammar upstream uses: both quote styles, bare keys, a trailing comma', () => {
    assert.deepEqual(parseObjectLiteral(`{ a: 'one', "b": "two", }`, 'fixture'), {
      a: 'one',
      b: 'two',
    });
  });

  it('reads the JSON scalars and containers it also accepts', () => {
    assert.deepEqual(
      parseObjectLiteral(`{ n: -2.5e3, i: 0, t: true, f: false, z: null }`, 'fixture'),
      { n: -2500, i: 0, t: true, f: false, z: null },
    );
    assert.deepEqual(parseObjectLiteral(`{ a: ['x', 1,], o: { k: 'v' } }`, 'fixture'), {
      a: ['x', 1],
      o: { k: 'v' },
    });
  });

  it('reads the escape sequences a string value may carry', () => {
    assert.deepEqual(parseObjectLiteral(`{ a: 'it\\'s', b: "\\u00e9\\n\\\\" }`, 'fixture'), {
      a: "it's",
      b: 'é\n\\',
    });
  });

  // The point of the whole function: this used to be `new Function(\`return ${literal}\`)()`,
  // which ran whatever an unpinned third-party repository put here, weekly in CI and on any
  // maintainer's machine. Each case below is a payload that evaluation would have executed.
  it('throws on an expression that would run code, rather than evaluating it', () => {
    for (const literal of [
      `{ title: (globalThis.x = 1, 'a') }`,
      `{ title: (() => { return 1; })() }`,
      `{ title: process.env.HOME }`,
      '{ title: `template` }',
      `{ title: require('fs') }`,
    ]) {
      assert.throws(() => parseObjectLiteral(literal, 'fixture'), /fixture:/, literal);
    }
    // Read through Reflect: `x` is not a declared global, which is the point of the check.
    assert.equal(Reflect.get(globalThis, 'x'), undefined);
  });

  it('throws on anything else outside the grammar', () => {
    for (const literal of [
      `{ title: undefined }`, // an identifier that is not true/false/null
      `{ title: 1 + 1 }`, // an operator
      `{ /* c */ title: 1 }`, // a comment
      `{ title: 'a', title: 'b' }`, // a duplicate key
      `{ title: 'unterminated }`,
      `{ title: 'a' } trailing`,
      `{ title: '\nnewline' }`,
      `{ title: '\\q' }`, // an escape the grammar does not define
    ]) {
      assert.throws(() => parseObjectLiteral(literal, 'fixture'), /fixture:/, literal);
    }
  });

  it('names the file and the line, because the run stops on a page nobody has open', () => {
    assert.throws(
      () => parseObjectLiteral(`{\n  title: 'a',\n  description: oops,\n}`, 'src/app/x/page.mdx'),
      /src\/app\/x\/page\.mdx: expected a string.*line 3/s,
    );
  });

  it('keeps a `__proto__` key as an ordinary property instead of writing the prototype', () => {
    const parsed = parseObjectLiteral(`{ "__proto__": { "polluted": true } }`, 'fixture');
    assert.equal(
      typeof parsed === 'object' && parsed !== null && Object.hasOwn(parsed, '__proto__'),
      true,
    );
    assert.equal(Reflect.get({}, 'polluted'), undefined);
  });
});

describe('yamlScalar', () => {
  it('single-quotes a plain value', () => {
    assert.equal(yamlScalar('Hello World'), "'Hello World'");
  });

  it('doubles an apostrophe so the scalar stays valid YAML', () => {
    assert.equal(yamlScalar("Arbitrum's SDK"), "'Arbitrum''s SDK'");
  });
});

describe('renderFrontmatter', () => {
  const block = renderFrontmatter({ title: 'T', description: 'D' }, DEFAULTS);

  it('emits the five fields this repo requires, in the committed order', () => {
    assert.deepEqual(block.split('\n'), [
      '---',
      "title: 'T'",
      "description: 'D'",
      "content_type: 'concept'",
      'author: gblanchemain',
      'sme: gblanchemain',
      '---',
    ]);
  });
});

describe('rewriteRelativeLinks', () => {
  const options = {
    sections: SECTIONS,
    baseUrl: '/docs/stylus/stylus-by-example',
    context: 'fixture',
  };

  it('resolves a same-directory link against the section that publishes the slug', () => {
    assert.equal(
      rewriteRelativeLinks('See [ABI Encode](./abi_encode).', options),
      'See [ABI Encode](/docs/stylus/stylus-by-example/basic_examples/abi_encode).',
    );
  });

  it('resolves against the owning section, not a hardcoded one', () => {
    // Upstream's version of this rule hardcodes `basic_examples`, which is only ever right
    // because the one relative link in the published set happens to live there.
    assert.equal(
      rewriteRelativeLinks('See [ERC-20](./erc20).', options),
      'See [ERC-20](/docs/stylus/stylus-by-example/applications/erc20).',
    );
  });

  it('leaves an absolute link alone', () => {
    const link = 'See [the docs](https://docs.arbitrum.io/stylus).';
    assert.equal(rewriteRelativeLinks(link, options), link);
  });

  it('preserves Rust strings and doc comments while rewriting the same link in prose', () => {
    const code = [
      '```rust',
      'let link = "[ABI Encode](./abi_encode)";',
      '/// See [Arrays](./arrays).',
      '```',
    ].join('\n');
    assert.equal(
      rewriteRelativeLinks(`${code}\n\nSee [ABI Encode](./abi_encode).`, options),
      `${code}\n\nSee [ABI Encode](/docs/stylus/stylus-by-example/basic_examples/abi_encode).`,
    );
  });

  it('preserves tilde fences, longer fences and inline code spans', () => {
    for (const code of [
      '~~~rust\n/// [Arrays](./arrays)\n~~~',
      '````markdown\n```rust\n```\n[Arrays](./arrays)\n````',
      '`[Arrays](./arrays)`',
      '``a `backtick` and [Arrays](./arrays)``',
      '``a multiline\n[Arrays](./arrays) span``',
    ]) {
      assert.equal(rewriteRelativeLinks(code, options), code);
    }
  });

  it('preserves frontmatter and keeps Unicode offsets when rewriting multiple prose links', () => {
    const frontmatter = '---\ntitle: "🦀 [Arrays](./arrays)"\n---\n\n';
    const prose = '🦀 [ABI Encode](./abi_encode) and [ERC-20](./erc20).';
    assert.equal(
      rewriteRelativeLinks(frontmatter + prose, options),
      frontmatter +
        '🦀 [ABI Encode](/docs/stylus/stylus-by-example/basic_examples/abi_encode) and ' +
        '[ERC-20](/docs/stylus/stylus-by-example/applications/erc20).',
    );
  });

  it('throws on a link to an example this site does not publish', () => {
    // Otherwise it ships as a 404 that only check-links catches, after the page is committed.
    assert.throws(
      () => rewriteRelativeLinks('See [Arrays](./arrays).', options),
      /this site does not publish/,
    );
  });
});

describe('insertNotForProductionBanner', () => {
  it('lands the banner above the first Rust fence, under the heading that introduces it', () => {
    const { content, inserted } = insertNotForProductionBanner(
      '### Examples\n\n```rust\nfn main() {}\n```\n',
      INCLUDE,
    );
    assert.equal(inserted, true);
    const lines = content.split('\n').filter((line) => line !== '');
    assert.deepEqual(lines.slice(0, 3), ['### Examples', INCLUDE, '```rust']);
  });

  it('inserts once, ahead of the first fence only', () => {
    const { content } = insertNotForProductionBanner(
      '# T\n\n```rust\na\n```\n\n## More\n\n```rust\nb\n```\n',
      INCLUDE,
    );
    assert.equal(content.split(INCLUDE).length - 1, 1);
  });

  it('reports rather than throws when the page has no Rust snippet', () => {
    const { content, inserted } = insertNotForProductionBanner(
      '# T\n\n```toml\na = 1\n```\n',
      INCLUDE,
    );
    assert.equal(inserted, false);
    assert.equal(content, '# T\n\n```toml\na = 1\n```\n');
  });
});

describe('buildPage', () => {
  const { content, metadata, banner } = build();

  it('replaces the metadata export with frontmatter and the do-not-edit marker', () => {
    assert.match(content, /^---\ntitle: 'Hello World • Stylus by Example'\n/);
    assert.match(content, /---\n\n\{\/\* AUTOGENERATED\. \*\/\}\n/);
    assert.doesNotMatch(content, /export const metadata/);
  });

  it('inserts dollar sequences in metadata literally', () => {
    for (const value of ['$1', '$10', '$$', '$&', '$`', "$'"]) {
      const metadata = { title: `Title ${value}`, description: `Buy a token for ${value}.` };
      const source = `export const metadata = ${JSON.stringify(metadata)};\n\n# Example\n`;
      const { content } = build(source);
      assert.equal(
        content,
        `${renderFrontmatter(metadata, DEFAULTS)}\n\n{/* AUTOGENERATED. */}\n\n# Example\n`,
        `metadata containing ${value} must round-trip without replacement expansion`,
      );
    }
  });

  it("keeps upstream's Begin Content marker where upstream put it", () => {
    assert.match(content, /\{\/\* AUTOGENERATED\. \*\/\}\n\n\{\/\* Begin Content \*\/\}\n/);
  });

  it('rewrites the relative link and inserts the banner', () => {
    assert.match(content, /\(\/docs\/stylus\/stylus-by-example\/basic_examples\/abi_encode\)/);
    assert.ok(content.includes(INCLUDE));
    assert.equal(banner, true);
  });

  it('hands back the parsed metadata, so the runner can report on it', () => {
    assert.equal(metadata.title, 'Hello World • Stylus by Example');
  });

  it('leaves the body below the banner untouched', () => {
    assert.match(content, /```rust\nconsole!\("hello there!"\);\n```/);
  });
});

describe('buildSectionMeta', () => {
  it('keeps the listed order and appends the catch-all the committed files carry', () => {
    assert.deepEqual(buildSectionMeta({ title: 'Applications', pages: ['erc20', 'erc721'] }), {
      title: 'Applications',
      pages: ['erc20', 'erc721', '...'],
    });
  });
});

describe('stylus-examples.data.ts', () => {
  it('names a page that exists for every allowlist entry', () => {
    for (const section of sections) {
      for (const slug of section.pages) {
        const file = path.join(outputDir, section.dir, `${slug}.mdx`);
        assert.ok(fs.existsSync(file), `${file} is listed in the data file but does not exist`);
      }
    }
  });

  it('lists every committed page, so none is left unmanaged by the generator', () => {
    for (const section of sections) {
      const dir = path.join(outputDir, section.dir);
      const committed = fs
        .readdirSync(dir)
        .filter((name) => name.endsWith('.mdx'))
        .map((name) => name.replace(/\.mdx$/, ''));
      assert.deepEqual([...committed].sort(), [...section.pages].sort());
    }
  });

  it('matches the committed meta.json, which is what fixes the sidebar order', () => {
    for (const section of sections) {
      const meta: unknown = JSON.parse(
        fs.readFileSync(path.join(outputDir, section.dir, 'meta.json'), 'utf-8'),
      );
      assert.deepEqual(meta, buildSectionMeta(section));
    }
  });
});
