/**
 * generate-stylus-examples: regenerate content/docs/stylus/stylus-by-example/ from
 * `offchainlabs/stylus-by-example`.
 *
 * Usage:
 *   pnpm stylus:generate                            # clone the upstream repo and write the pages
 *   pnpm stylus:generate --source-path ../sbe       # read an existing clone instead
 *   pnpm stylus:check                               # exit 1 with a diff summary when stale
 *
 * `--source-path` also reads from `STYLUS_REPO_PATH`; the flag wins when both are set.
 *
 * Why this exists: the pages were ported by hand from a Docusaurus pipeline that lived in
 * arbitrum-docs (`scripts/sync-stylus-content.js` plus a job in `update-external-content.yml`).
 * That pipeline does not survive arbitrum-docs being archived, and without it an edit to
 * `offchainlabs/stylus-by-example` reaches this site through nobody and nothing.
 *
 * Unlike `generate-cli-reference.ts` this pins no upstream ref. Nitro has releases and
 * content/vars.json already names the one the docs describe; stylus-by-example has neither, and
 * the site has always tracked its default branch, so a pin here would only be a second number to
 * forget to bump.
 *
 * That makes `--check` network-dependent and dependent on someone else's default branch, which is
 * why it is not a CI gate: it would redden every open PR the moment an unrelated repository
 * edited a page. It runs weekly in `upstream-refresh.yml`, where a change becomes a PR instead.
 *
 * Ported from arbitrum-docs `scripts/sync-stylus-content.js`.
 */
import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import type { Options as PrettierOptions } from 'prettier';

import {
  frontmatterDefaults,
  notForProductionInclude,
  outputDir,
  outputUrl,
  repoUrl,
  sections,
  sourceRoot,
} from './data/stylus-examples.data.ts';
import { stringifyMeta } from './lib/doc-links.ts';
import {
  StaleFileError,
  type WriteOrCheckOptions,
  isCheckMode,
  runScript,
  writeOrCheck,
} from './lib/generated-partial.ts';
import { diffSummary } from './lib/line-diff.ts';
import { buildPage, buildSectionMeta } from './lib/stylus-examples.ts';

/** See MDX_FORMAT in generate-precompile-tables.ts: the generator owns these files' shape. */
const MDX_FORMAT: PrettierOptions = {
  parser: 'mdx',
  printWidth: 9999,
  proseWrap: 'preserve',
  plugins: [],
};

/** The comment that tells a human editing one of these pages that they are editing the wrong file. */
const MARKER =
  '{/* AUTOGENERATED. Do not edit by hand. Run `pnpm stylus:generate`. Source: ' +
  'https://github.com/offchainlabs/stylus-by-example */}';

interface Args {
  check: boolean;
  sourcePath: string | null;
}

function parseArgs(argv: string[]): Args {
  const args: Args = { check: isCheckMode(), sourcePath: process.env.STYLUS_REPO_PATH ?? null };
  for (let i = 0; i < argv.length; i++) {
    const value = argv[i + 1];
    if (argv[i] === '--source-path' && value) {
      args.sourcePath = value;
      i++;
    }
  }
  return args;
}

/**
 * Put the upstream tree under `workDir` and return the directory holding the app-router pages.
 *
 * A local clone is read through `git archive`, not off the working tree, so a checkout with local
 * edits or a stale index cannot leak into the generated pages — the same rule
 * `generate-cli-reference.ts` applies to Nitro.
 */
function materializeSource({
  sourcePath,
  workDir,
}: {
  sourcePath: string | null;
  workDir: string;
}): string {
  const treeDir = path.join(workDir, 'stylus-by-example');

  if (sourcePath) {
    const repo = path.resolve(sourcePath);
    fs.mkdirSync(treeDir, { recursive: true });
    const archive = execFileSync('git', ['archive', 'HEAD'], {
      cwd: repo,
      maxBuffer: 256 * 1024 * 1024,
    });
    execFileSync('tar', ['-x', '-C', treeDir], { input: archive, maxBuffer: 256 * 1024 * 1024 });
  } else {
    console.log(`cloning ${repoUrl} (shallow)`);
    execFileSync('git', ['clone', '--depth', '1', '--quiet', repoUrl, treeDir], {
      encoding: 'utf-8',
    });
  }

  const appDir = path.join(treeDir, sourceRoot);
  if (!fs.existsSync(appDir)) {
    throw new Error(
      `${path.join(sourcePath ?? repoUrl, sourceRoot)} does not exist; the upstream repository ` +
        `has been restructured and scripts/data/stylus-examples.data.ts needs sourceRoot updated`,
    );
  }
  return appDir;
}

/**
 * Name the upstream examples this site does not publish.
 *
 * The allowlist is the reason the published set is stable, and also the reason an example added
 * upstream would otherwise be invisible here forever. Reporting is the whole job: nothing is
 * generated for these, and the weekly refresh log is where somebody notices one worth porting.
 */
function reportUnpublished(appDir: string): void {
  for (const section of sections) {
    const dir = path.join(appDir, section.dir);
    if (!fs.existsSync(dir)) continue;
    const upstream = fs
      .readdirSync(dir, { withFileTypes: true })
      .filter((entry) => entry.isDirectory())
      .map((entry) => entry.name)
      .filter((name) => fs.existsSync(path.join(dir, name, 'page.mdx')));

    const unpublished = upstream.filter((name) => !section.pages.includes(name));
    if (unpublished.length > 0) {
      console.log(
        `  ${section.dir}: ${unpublished.length} upstream example(s) not published here: ` +
          unpublished.join(', '),
      );
    }
  }
}

/**
 * Write (or check) one file, printing the line diff before rethrowing a staleness error.
 *
 * Every generator in this repo does this, for the same reason: "the file is stale" does not tell
 * a reviewer of the weekly refresh PR whether a code sample changed or only whitespace did.
 */
async function emit(
  filePath: string,
  content: string,
  options: WriteOrCheckOptions,
): Promise<boolean> {
  try {
    return await writeOrCheck(filePath, content, options);
  } catch (error) {
    // `formatted` is optional on the error's type but always set in check mode, the only mode
    // that throws it.
    if (error instanceof StaleFileError && error.formatted !== undefined) {
      const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf-8') : '';
      console.error(`${path.relative(process.cwd(), filePath)}:`);
      console.error(diffSummary(current, error.formatted));
    }
    throw error;
  }
}

async function main(): Promise<void> {
  const { check, sourcePath } = parseArgs(process.argv.slice(2));
  const workDir = fs.mkdtempSync(path.join(os.tmpdir(), 'stylus-by-example-'));

  let written = 0;
  let missingBanner: string[] = [];
  try {
    const appDir = materializeSource({ sourcePath, workDir });

    // A report, not a failure, and printed before the writes so it survives a staleness throw:
    // this is how an example added upstream gets noticed at all.
    reportUnpublished(appDir);

    for (const section of sections) {
      for (const slug of section.pages) {
        const context = path.join(sourceRoot, section.dir, slug, 'page.mdx');
        const sourceFile = path.join(appDir, section.dir, slug, 'page.mdx');
        if (!fs.existsSync(sourceFile)) {
          throw new Error(
            `${context} is gone from upstream. Either it was renamed, in which case update ` +
              `scripts/data/stylus-examples.data.ts and add a redirect, or it was deleted, in ` +
              `which case drop it from that file and from the page that links to it.`,
          );
        }

        const { content, banner } = buildPage({
          source: fs.readFileSync(sourceFile, 'utf-8'),
          context,
          marker: MARKER,
          frontmatterDefaults,
          sections,
          baseUrl: outputUrl,
          include: notForProductionInclude,
        });
        if (!banner) missingBanner.push(context);

        const target = path.join(outputDir, section.dir, `${slug}.mdx`);
        if (await emit(target, content, { check, overrides: MDX_FORMAT })) written++;
      }

      const metaPath = path.join(outputDir, section.dir, 'meta.json');
      // Not Prettier-formatted: see the `format: false` note on writeOrCheck. `stringifyMeta`
      // is the same writer `pnpm move-doc` uses, so the two agree on this file's shape.
      const meta = stringifyMeta(buildSectionMeta(section));
      if (await emit(metaPath, meta, { check, format: false })) written++;
    }
  } finally {
    fs.rmSync(workDir, { recursive: true, force: true });
  }

  const pages = sections.reduce((total, section) => total + section.pages.length, 0);
  console.log(
    check
      ? `stylus by example: up to date (${pages} page(s)).`
      : `stylus by example: ${pages} page(s) read, ${written} file(s) written.`,
  );

  // A report rather than a failure: a page loses its not-for-production banner when upstream
  // rewrites its first snippet in another language, which is a content decision, not a bug here.
  if (missingBanner.length > 0) {
    console.warn(
      `warning: no \`\`\`rust block, so no not-for-production banner, in:\n` +
        missingBanner.map((c) => `  - ${c}`).join('\n'),
    );
  }
}

runScript(main);
