project_id: '505004'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  # JSON translation files
  - source: /arbitrum-docs/**/*
    translation: /website/i18n/%two_letters_code%/**/%original_file_name%
