#!/usr/bin/env sh

cd website

# Check if globalVars.js has staged changes
if git diff --cached --name-only | grep -q "src/resources/globalVars.js"; then
  echo "🔄 Updating variable references..."
  yarn update_variable_refs

  echo "🔄 globalVars.js changed, running precompiles reference table generator..."
  yarn generate_precompiles_ref_tables

  echo "💅 running formatter"
  yarn format
fi

# Check for missing redirects
yarn tsx scripts/check-redirects.ts
CHECK_REDIRECTS_EXIT_CODE=$?

if [ $CHECK_REDIRECTS_EXIT_CODE -ne 0 ]; then
  echo "❌ Error: The redirect checker found issues that need to be addressed. Please check the output above and fix any issues before committing."
  exit 1
fi

echo "\n✅ Pre-commit tasks completed\n💡 Note: To bypass hooks, use git commit --no-verify"