name: Check format
run-name: Checking format

on:
  pull_request:
    branches:
      - master

jobs:
  install:
    name: 'Install'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install node_modules
        uses: OffchainLabs/actions/node-modules/install@main
        with:
          install-command: yarn install --frozen-lockfile
          cache-key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

  check-formatting:
    name: 'Check Formatting'
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install node_modules
        uses: OffchainLabs/actions/node-modules/install@main
        with:
          cache-key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}

      - name: Check formatting with Prettier
        run: yarn format:check

  label-merge-conflicts:
    name: 'Label Merge Conflicts'
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.pull_request.state == 'open' }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Label conflicting PRs
        uses: prince-chrismc/label-merge-conflicts-action@c1a2b3c4d5e6f7g8h9i0j1k2l3m4n5o6p7q8r9s0
        with:
          conflict_label_name: 'merge conflict(s)'
          github_token: ${{ secrets.GITHUB_TOKEN }}
          conflict_comment: 'This pull request has merge conflicts that need to be resolved before it can be merged.'
